## Summary of this Project
* external documents
> * around 1.8M characters across 7 source documents (745 pages)
* parameter configurations
> * chunk_size = 550
> * chunk_overlap = 120
> * embedding_model = "BAAI/bge-m3"
>> * embedding dimension = 1024
> * top_k = 12
> * reranker_top_k = 8
>> * reranker_model = "cross-encoder/ms-marco-MiniLM-L-6-v2"
> * llm_model = "llama-3.1-8b-instant"
> * judge_model = "openai/gpt-oss-120b"
* evalation set
> * 40 questions drafted with Claude (Anthropic), verified against source documents.
* performance metrics
> * recall: 0.97
> * answer accuracy: 0.92
> * citation validity: 0.97
>> * the proportion of generated answers in which every cited source tag refers to a chunk that was genuinely present in the retrieved context, verifying that no citation was fabricated or misattributed to a non-existent source.
> * faithfulness: 0.82
>> * the proportion of generated answers judged by an LLM-as-judge to be holistically supported by the combined text of all cited context, i.e. the answer's claims are grounded in the retrieved evidence rather than the model's own prior knowledge.
* the failures stem from the same root cause:
> * the model resolves ambiguity between multiple similar-looking candidates by relying on superficial cues (proximity, file grouping) rather than verifying the specific label/entity named in the text itself.

## 建立模組目錄

In [ ]:
## create modular root folder
import os

os.makedirs('RAG_module', exist_ok = True)
os.makedirs('RAG_module/data', exist_ok = True)

## `requirements.txt`
* 安裝列表

In [ ]:
%%writefile RAG_module/requirements.txt
llama-index
llama-index-readers-file
llama-index-embeddings-google-genai
llama-index-vector-stores-qdrant
google-genai
groq
qdrant-client
rank_bm25
sentence-transformers
jieba

Writing RAG_module/requirements.txt

In [ ]:
!pip install -q -r RAG_module/requirements.txt

## `config.py`
* 外部參數設定

In [ ]:
%%writefile RAG_module/config.py
from google.colab import userdata
import os

# external data
DOCUMENT_DIR = "RAG_module/data"

# chunking related
CHUNK_SIZE = 450
CHUNK_OVERLAP = 120

# embedding model
EMBEDDING_MODEL = "BAAI/bge-m3"
EMBEDDING_DIM = 1024
# EMBEDDING_MODEL = "gemini-embedding-001"
# EMBEDDING_DIM = 3072

# collection
COLLECTION_NAME = "demo"

# retrieval
TOP_K = 12

# reranking related
#RERANKER_MODEL = "cross-encoder/ms-marco-MiniLM-L-6-v2"
RERANKER_MODEL = "BAAI/bge-reranker-v2-m3"
RERANKER_TOP_K = 8

# LLM
LLM_MODEL = "llama-3.1-8b-instant"
JUDGE_MODEL = "openai/gpt-oss-120b"
# LLM_MODEL = "gemini-2.0-flash-lite"
# JUDGE_MODEL = "gemini-2.0-flash-lite"

Writing RAG_module/config.py

## `api.py`

In [ ]:
%%writefile RAG_module/api.py
import os
from google.colab import userdata

os.environ["HF_TOKEN"] = userdata.get("HF_TOKEN")
os.environ["GOOGLE_API_KEY"] = userdata.get("GOOGLE_API_KEY")
os.environ["GROQ_API_KEY"] = userdata.get("GROQ_API_KEY")

Writing RAG_module/api.py

## `test.txt`
在RAG的情境裡，就是外部文件

In [ ]:
## 解壓縮外部文件
!unzip -qj RAG_files.zip -d /content/RAG_module/data

In [ ]:
%%writefile RAG_module/data/test.txt
RAG stands for Retrieval Augmented Generation.

A RAG system retrieves relevant documents before sending context to the language model.

Qdrant is a vector database.

LlamaIndex is a framework for building RAG systems.

Gemini is a large language model developed by Google.

Writing RAG_module/data/test.txt

## `document_corrections.py`
* 讀取的外部文件，可能會有一些因編碼錯誤而在讀取時產生錯誤的文字

In [ ]:
%%writefile RAG_module/document_corrections.py

_KNOWN_OCR_ERRORS = {
    "貨幣政策工具.pdf": [
        ("店 、1,000", "500萬元、1,000"),
        ("國庫六 發 行條例", "國庫券發行條例"),
    ],
}


def apply_ocr_corrections(documents):
  # 先統計每個檔案、每筆修正，總共命中幾次
  hit_counts = {
      filename: {wrong: 0 for wrong, _ in corrections}
      for filename, corrections in _KNOWN_OCR_ERRORS.items()
  }

  for doc in documents:
    filename = doc.metadata.get("file_name")
    corrections = _KNOWN_OCR_ERRORS.get(filename)
    if not corrections:
      continue

    text = doc.get_content()
    changed = False
    for wrong, correct in corrections:
      if wrong in text:
        text = text.replace(wrong, correct)
        changed = True
        hit_counts[filename][wrong] += 1
        print(f"[ocr_correction] {filename}（page_label = "
              f"{doc.metadata.get('page_label')}）：「{wrong}」→「{correct}」")

    if changed:
      doc.set_content(text)


  # 檢查有沒有任何一筆修正，整份文件都完全沒命中
  made_corrections = True
  for filename, corrections in _KNOWN_OCR_ERRORS.items():
    for wrong, correct in corrections:
      if hit_counts.get(filename, {}).get(wrong, 0) == 0:
        made_corrections = False

  if len(_KNOWN_OCR_ERRORS) == 0:
    print(f"no corrections on the documents are needed.")

  else:
    if made_corrections:
      print(f"some known errors are corrected for the documents.")

    else:
      print(f"corrections are needed but none has been made.")

  return documents

Writing RAG_module/document_corrections.py

## `loader.py`
* 專心處理 Document
* 輸出的型態為 list of Documents

In [ ]:
%%writefile RAG_module/loader.py
from llama_index.core import (
    SimpleDirectoryReader
)

from RAG_module.config import DOCUMENT_DIR
from RAG_module.document_corrections import apply_ocr_corrections, _KNOWN_OCR_ERRORS

def load_documents():
  documents = SimpleDirectoryReader(DOCUMENT_DIR).load_data()
  documents = apply_ocr_corrections(documents)
  return documents

Writing RAG_module/loader.py

## `metadata_loader.py`
* 輸入文件層級的 metadata

In [ ]:
%%writefile RAG_module/metadata_loader.py
import csv

# 主題分類（供 metadata filter 與 BM25 領域詞彙比對使用）
CATEGORIES = [
    "支付清算",
    "貨幣政策",
    "氣候金融",
    "央行比較法制",
    "其他",
]

# 文件性質
DOC_TYPES = [
    "本行政策報告",
    "國際準則中譯本",
    "比較法選輯",
    "制度說明手冊",
    "其他",
]

_METADATA_CSV_PATH = "RAG_module/document_metadata.csv"


def load_document_metadata(csv_path=_METADATA_CSV_PATH):
  """讀取文件層級 metadata，回傳以 filename 為 key 的 lookup dict。

  回傳格式：
  {
    "貨幣政策工具.pdf": {
        "title": "貨幣政策工具",
        "category": "貨幣政策",
        "publish_date": "",
        "issuing_unit": "中央銀行",
        "doc_type": "制度說明手冊",
    },
    ...
  }
  """
  metadata_lookup = {}
  with open(csv_path, newline="", encoding="utf-8") as f:
    reader = csv.DictReader(f)
    for row in reader:
      filename = row.pop("filename")
      metadata_lookup[filename] = row
  return metadata_lookup


def get_metadata_for_file(filename, metadata_lookup):
  """取得單一檔案的 metadata；若找不到，回傳空值欄位並印出警告。

  這裡刻意不拋例外——文件蒐集階段可能會陸續加新檔案，
  找不到 metadata 時應該讓 pipeline 繼續跑，而不是整個中斷，
  但要讓使用者知道有檔案漏填 metadata。
  """
  if filename not in metadata_lookup:
    print(f"[metadata_loader] 警告：找不到 {filename} 的 metadata，"
          f"請確認 document_metadata.csv 是否有補上這筆資料。")
    return {
        "title": filename,
        "category": "其他",
        "publish_date": "",
        "issuing_unit": "",
        "doc_type": "其他",
    }
  return metadata_lookup[filename]

Writing RAG_module/metadata_loader.py

In [ ]:
## check if each document name matches its corresponding column in the metadata csv file
import unicodedata
from RAG_module.metadata_loader import load_document_metadata
from RAG_module.loader import load_documents


def check_metadata_completeness(csv_path = None):
  """檢查 CSV 裡有哪些必要欄位是空的，方便你補資料時一次看完。

  category / doc_type 是 retrieval filter 會用到的關鍵欄位，缺漏會直接
  影響檢索效果，因此獨立列出；publish_date 缺漏則僅列為提醒。
  """
  metadata_lookup = (
      load_document_metadata(csv_path) if csv_path else load_document_metadata()
  )
  missing_critical = []
  missing_date = []
  for filename, meta in metadata_lookup.items():
    if not meta.get("category") or not meta.get("doc_type"):
      missing_critical.append(filename)
    if not meta.get("publish_date"):
      missing_date.append(filename)

  if missing_critical:
    print("[test_metadata] 缺少 category 或 doc_type（建議先補齊再進 Step 3）：")
    for f in missing_critical:
      print(f"  - {f}")

  if missing_date:
    print("[test_metadata] 缺少 publish_date（可之後補，先不影響 retrieval）：")
    for f in missing_date:
      print(f"  - {f}")

  if not missing_critical and not missing_date:
    print("[test_metadata] metadata 齊全，沒有缺漏欄位。")

  return {"missing_critical": missing_critical, "missing_date": missing_date}


def verify_filenames_match(documents, csv_path=None):
  """確認 loader 讀進來的文件檔名跟 metadata csv 完全對得上。

  統一先做 NFC 正規化再比對，避免不同來源（例如 zip 解壓縮）造成的
  NFC/NFD 編碼差異誤判成「檔名不一致」。

  用法：
    from RAG_module.loader import load_documents
    from test_metadata import verify_filenames_match
    documents = load_documents()
    verify_filenames_match(documents)
  """
  metadata_lookup = (
      load_document_metadata(csv_path) if csv_path else load_document_metadata()
  )

  def _norm(name):
    return unicodedata.normalize("NFC", name) if name else name

  loader_filenames = {_norm(doc.metadata.get("file_name")) for doc in documents}
  csv_filenames = {_norm(f) for f in metadata_lookup.keys()}

  only_in_loader = loader_filenames - csv_filenames
  only_in_csv = csv_filenames - loader_filenames

  if not only_in_loader and not only_in_csv:
    print(f"[test_metadata] 檔名比對通過，{len(loader_filenames)} 份文件全部對得上 metadata。")
    return True

  if only_in_loader:
    print("[test_metadata] 這些文件有讀進來，但 CSV 裡沒有對應的 metadata：")
    for f in sorted(only_in_loader):
      print(f"  - {f}")

  if only_in_csv:
    print("[test_metadata] CSV 裡有這些檔名，但 loader 沒讀到對應文件"
          "（可能是檔案還沒放進 DOCUMENT_DIR，或檔名打錯）：")
    for f in sorted(only_in_csv):
      print(f"  - {f}")

  return False


documents = load_documents()
verify_filenames_match(documents)

[ocr_correction] 貨幣政策工具.pdf（page_label = 12）：「店 、1,000」→「500萬元、1,000」
[ocr_correction] 貨幣政策工具.pdf（page_label = 13）：「國庫六 發 行條例」→「國庫券發行條例」
some known errors are corrected for the documents.
[test_metadata] 檔名比對通過，7 份文件全部對得上 metadata。

True

## `kb_manager.py`
* 負責 knowledge base management

In [ ]:
%%writefile RAG_module/kb_manager.py
import os
import json
import hashlib

CHECKSUM_PATH = "RAG_module/checksum.json"

def compute_checksum(document_dir, embedding_model):
  hasher = hashlib.md5()
  for filename in sorted(os.listdir(document_dir)):
    filepath = os.path.join(document_dir, filename)

    if not os.path.isfile(filepath):
      continue

    with open(filepath, "rb") as f:
      hasher.update(f.read())

  hasher.update(embedding_model.encode("utf-8"))

  return hasher.hexdigest()

def load_checksum():
  if not os.path.exists(CHECKSUM_PATH):
    return None

  with open(CHECKSUM_PATH, "r") as f:
    return json.load(f).get("checksum")

def save_checksum(checksum):
  with open(CHECKSUM_PATH, "w") as f:
    json.dump({"checksum": checksum}, f)

def is_kb_outdated(document_dir, embedding_model):
  current = compute_checksum(document_dir, embedding_model)
  saved = load_checksum()
  return current != saved, current

Writing RAG_module/kb_manager.py

## `chunker.py`
* 專心處理 TextNode
* chunking 在此進行

In [ ]:
%%writefile RAG_module/chunker.py
from llama_index.core.node_parser import SentenceSplitter

def create_chunker(chunk_size, chunk_overlap):
  return SentenceSplitter(chunk_size = chunk_size,
                          chunk_overlap = chunk_overlap)


def create_nodes(documents, chunk_size, chunk_overlap):
  chunker = create_chunker(chunk_size, chunk_overlap)
  nodes = chunker.get_nodes_from_documents(documents)

  return nodes

Writing RAG_module/chunker.py

In [ ]:
## debug: 檢查「店」這個字在「貨幣政策工具.pdf」裡出現的所有位置，
## 確認要用多精確的字串才能安全替換，不誤傷其他正確內容
from RAG_module.loader import load_documents
from RAG_module.chunker import create_nodes
from RAG_module.config import CHUNK_SIZE, CHUNK_OVERLAP

documents = load_documents()
nodes = create_nodes(documents, CHUNK_SIZE, CHUNK_OVERLAP)

target_file = "貨幣政策工具.pdf"
target_nodes = [n for n in nodes if n.metadata.get("file_name") == target_file]

print("=== 「店」字出現的所有位置（前後各20字）===")
for n in target_nodes:
    content = n.get_content()
    idx = content.find("店")
    while idx != -1:
        print(f"[page_label={n.metadata.get('page_label')}]")
        print(repr(content[max(0, idx-20): idx+20]))
        print()
        idx = content.find("店", idx + 1)

print("=== 確認「國庫六發行條例」的完整上下文 ===")
for n in target_nodes:
    content = n.get_content()
    if "國庫六" in content:
        idx = content.find("國庫六")
        print(f"[page_label={n.metadata.get('page_label')}]")
        print(repr(content[max(0, idx-20): idx+20]))

[ocr_corrections correction] 貨幣政策工具.pdf（page_label = 12）：「店 、1,000」→「500萬元、1,000」
[ocr_corrections correction] 貨幣政策工具.pdf（page_label = 13）：「國庫六 發 行條例」→「國庫券發行條例」
corrections are needed but none has been made.
=== 「店」字出現的所有位置（前後各20字）===
=== 確認「國庫六發行條例」的完整上下文 ===

In [ ]:
## test: 檢視 chunker 切出來的結果，特別看表格/條列密集處切得好不好
from RAG_module.loader import load_documents
from RAG_module.chunker import create_nodes
from RAG_module.config import CHUNK_SIZE, CHUNK_OVERLAP

documents = load_documents()
nodes = create_nodes(documents, CHUNK_SIZE, CHUNK_OVERLAP)

print(f"文件數：{len(documents)}，切出的 chunk 總數：{len(nodes)}")
print()

# 1. 每份文件切出幾個 chunk，順便看 chunk 長度分布（太短的 chunk 通常代表切壞了）
from collections import defaultdict

chunks_by_file = defaultdict(list)
for node in nodes:
    fname = node.metadata.get("file_name", "未知檔名")
    chunks_by_file[fname].append(node)

print("=== 每份文件的 chunk 數與長度統計 ===")
for fname, file_nodes in chunks_by_file.items():
    lengths = [len(n.get_content()) for n in file_nodes]
    avg_len = sum(lengths) / len(lengths)
    print(f"{fname}：{len(file_nodes)} chunks，平均長度 {avg_len:.0f} 字，"
          f"最短 {min(lengths)} 字，最長 {max(lengths)} 字")
print()

# 2. 挑幾個關鍵字，把包含這些字的 chunk 印出來，重點看表格/條列是否被切斷
#    「貨幣政策工具.pdf」裡的表格（表一~表三）跟利率數字是重點檢查對象
KEYWORDS_TO_INSPECT = ["表一", "表二", "表三", "準備率", "附買回", "重貼現"]

print("=== 包含指定關鍵字的 chunk 內容（檢查表格是否被切斷）===")
for keyword in KEYWORDS_TO_INSPECT:
    matched = [n for n in nodes if keyword in n.get_content()]
    if not matched:
        print(f"[關鍵字「{keyword}」沒有出現在任何 chunk 裡，可能被切壞或不存在]")
        continue
    print(f"--- 關鍵字「{keyword}」，共 {len(matched)} 個 chunk 命中，顯示第一個 ---")
    print(matched[0].get_content())
    print("...(chunk 結束)...")
    print()

# 3. 也印出「各國中央銀行法選輯」裡任一 chunk，檢查條號（第X條）是否完整
print("=== 各國中央銀行法選輯：隨機抽一個 chunk 看條文是否完整 ===")
for fname, file_nodes in chunks_by_file.items():
    if "中央銀行法選輯" in fname:
        sample = file_nodes[len(file_nodes) // 2]  # 抽中間那個，比較不會是封面/目錄
        print(f"[{fname}]")
        print(sample.get_content())
        print("...(chunk 結束)...")
        print()
        break

文件數：752，切出的 chunk 總數：4625

=== 每份文件的 chunk 數與長度統計 ===
一國支付系統發展之一般準則.pdf：677 chunks，平均長度 139 字，最短 2 字，最長 961 字
中華民國支付及清算系統.pdf：189 chunks，平均長度 143 字，最短 29 字，最長 242 字
各國中央銀行法選輯-2025年版-上冊.pdf：1398 chunks，平均長度 370 字，最短 0 字，最長 1391 字
各國中央銀行法選輯-2025年版-下冊.pdf：1431 chunks，平均長度 385 字，最短 0 字，最長 1124 字
因應氣候變遷策略方案.pdf：236 chunks，平均長度 150 字，最短 15 字，最長 847 字
支付與清算系統間之相互依存關係.pdf：597 chunks，平均長度 140 字，最短 1 字，最長 589 字
貨幣政策工具.pdf：97 chunks，平均長度 154 字，最短 23 字，最長 212 字

=== 包含指定關鍵字的 chunk 內容（檢查表格是否被切斷）===
[關鍵字「表一」沒有出現在任何 chunk 裡，可能被切壞或不存在]
--- 關鍵字「表二」，共 2 個 chunk 命中，顯示第一個 ---
「證券法（5728-1968）」第 1 條所定「證券」定義中，所稱
「由政府持有」等語後，接以「或由以色列銀行持有」等語。
「政府公司法（5735-1975）」附表二第18 項修正為以下內容：
「18. 依『以色列銀行法（5770-2010）』設置貨幣委員會及
理事會。」
「銀行（許可）法（5741-1981）」第 50B 條第(c)項所定「由
其決定比率」修正為「最大比率之減輕」。
...(chunk 結束)...

--- 關鍵字「表三」，共 1 個 chunk 命中，顯示第一個 ---
自民國 89 年 12 月至92 年 6 月, 中央 銀 行為刺激經濟景氣 , 調
降 各項中 央 銀 行利率 達十五次之多。有關中 央銀行利率的調整 , 可參閱 表三。
第 三節 ” 公 開 市 場操作
一、公 開 市 場操作 的意義 與目的
公開 市場操作為 中央銀 行經由 金融 市 場, 買 賣票債姜的 方式增減銀行 體
系 的準備 金,
...(chunk 結束)...

--- 關鍵字「準備率」，共 10 個 chunk 命中，顯示第一個 ---
各類相關實施程序及原則，包括應提準
備金之資產負債表內外適當項目、應提之準備率、必要時適
用之準備金提存期間及利率，以及存款或參與性資金異常提
領或合併、收購與分割時執行之交易，由本行決定之。
必要時，
上述機構留存流動性要求之條件及比率，由本行決定之。
...(chunk 結束)...

--- 關鍵字「附買回」，共 21 個 chunk 命中，顯示第一個 ---
系統參加者或集中交易對手之違約事件；
. 作業風險與財務風險之控管及營運不中斷；
. 財務損失分攤機制。
法規範例：
. CHIPS、Fedwire、CHAPS、Clearstream及其他結算與清算系統
等之系統規約；
. 主要附買回協議（國際證券自營商公會）；
5. 證券清算系統之法規架構
除前述第 2、3、4 節之法規型態外，尚包括：
.
...(chunk 結束)...

--- 關鍵字「重貼現」，共 24 個 chunk 命中，顯示第一個 ---
此類融通一般採取對
帳戶持有者之活期帳戶墊款或透支，該類融通
得以證券設質（如歐洲某些國家的倫巴放款）
或傳統票據重貼現方式，保障債權。

集中交易對手
central
counterparty(CCP)

擔任某些特定契約（例如在特定交易所執行之
契約）所有賣方之買方及所有買方之賣方的機
構。
...(chunk 結束)...

=== 各國中央銀行法選輯：隨機抽一個 chunk 看條文是否完整 ===
[各國中央銀行法選輯-2025年版-上冊.pdf]
(aA) in the case of a Government representative, through the
appointment by the President of the Republic, after consultation
with the Minister, of another person; and
(b) in the case of an elected director, by the election by the
shareholders at an ordinary general meeting of shareholders of a
person, confirmed by the Panel as a candidate as contemplated
in this Act, in the place of the director whose office has become
vacant, or by the appointment by the Board, subject to his or
her subsequent election by shareholders at the next ordinary
general meeting of the shareholders, of a person confirmed by
the Panel as a person suitable for possible election to the Board.
...(chunk 結束)...

In [ ]:
## test: 專項檢查「貨幣政策工具.pdf」是否有文字擷取（亂碼/缺字）問題
from RAG_module.loader import load_documents
from RAG_module.chunker import create_nodes
from RAG_module.config import CHUNK_SIZE, CHUNK_OVERLAP

documents = load_documents()
nodes = create_nodes(documents, CHUNK_SIZE, CHUNK_OVERLAP)

target_file = "貨幣政策工具.pdf"
target_nodes = [n for n in nodes if n.metadata.get("file_name") == target_file]

print(f"「{target_file}」共切出 {len(target_nodes)} 個 chunk")
print()

# 把全部 chunk 依序印出來（只有42個，全部看完也不會太長）
for i, node in enumerate(target_nodes):
    content = node.get_content()
    print(f"--- chunk {i} (長度 {len(content)} 字，page_label={node.metadata.get('page_label')}) ---")
    print(content)
    print()

「貨幣政策工具.pdf」共切出 97 個 chunk

--- chunk 0 (長度 156 字，page_label=1) ---
第四 章 ” 貨 幣政策工具
第四 章 貸 幣政策 工具
貨 幣政策 機 制為中央銀 行決策 的基本 架構 , 而 貨幣政策工具則為 中央銀
行 執行貨幣政策的手段 。發 幣政策 工具 透過對準備 發幣與金融業拆款利率的
影響 。將 影響 力傳送至其他的 經濟 金融變數 , 以 達成穩定 與發展的既定 目
慄。

--- chunk 1 (長度 106 字，page_label=1) ---
以 達成穩定 與發展的既定 目
慄。本章 以貨幣政策 工具為 主 題。依 序說明 我 國準備 金制度、貼 現窗口制
度、公開 市場操作、金 融機 構轉存款及選擇 性信用 管理 等制度的 運作與業務
操作 內 涵。

--- chunk 2 (長度 171 字，page_label=1) ---
第 一節 準備 金制度
一、準 備金制度 的意義 與目的
準備 金制度 為中央銀 行依法 要求金融機構依其負債 提存 一定比率的準備
金 , 以因應 支付需求 的制度。此處 的金融機構主要係 指具有吸收存款 與創造
貨 幣信用功能 的銀行。中 央銀 行要求 銀行提存準備 金的目的 為 :
(一 ) 銀 行本質上資產 期限長而負債 期限 短,

--- chunk 3 (長度 164 字，page_label=1) ---
透 過準備 金制度可建立 社會大眾
對 金融體系提供 充分 流動 性的信心。此 外 , 一 旦銀 行出現流動性 不 足
時 , 可 以存在中 央 銀 行的準備 金為擔保 , 向中 央銀 行申請 緊急 融通。
(二 ) 以準備 金制度中的準備 率做為 貨幣政策工具。透 過準備 率的調整。可 改
變銀行 體系 的信用 貸 放能力。

--- chunk 4 (長度 167 字，page_label=1) ---
透 過準備 率的調整。可 改
變銀行 體系 的信用 貸 放能力。進 而控制 貨幣總計數 或其他 重要金 融弦
數 , 以促進 經濟 金融的穩定 。
二 、現 行準備 金制度
我 國的準備 金制度 已行之有 年。除 於民國 83 年 11 月 為 減少拆款利率 每
月 三名週期性的波動 。將準備 金由按 旬計提 改為按月計提 以 外,

--- chunk 5 (長度 149 字，page_label=1) ---
將準備 金由按 旬計提 改為按月計提 以 外,85 年 9 月中
閃 銀行專歡事陛磺會議也審議通話人備 金制度 的改革建議 案 。86 年立法 通
過 修正「中 央銀 行法」第 二十三條 , 以 為改革的 法源依據 ,88 年 7 月 7 日正
% 參閱中 央銀 行專案 小組 (1996)。
97

--- chunk 6 (長度 187 字，page_label=2) ---
98 中 華民國中 央 銀 行之制度與功能
式 實施。改革 的方向 主要 包括 :
(一 ) 取 消準備率下 限。以 降低準備率
1. 對銀行 而 言。準 備金 形同凍結一部 分的營運資金 於中 央銀行 , 因此 如
果 準備率較 高 , 經 營成本 就較 大。銀 行會以拉 高放款利率 或壓低存款
利率 的方式 , 轉 嫁成 本, 因 而不利於 一般大眾的經濟福祉。
2.

--- chunk 7 (長度 187 字，page_label=2) ---
隨 著金融自由 化 的快速進 展。國 內非銀行 金融機構與銀行 之間 的囚
限 日益模燭 , 但 其資金 的吸收 卻 不必 受準備 金制度 的束縛 , 造 成對 銀
行 不公平 的競爭。
此外 , 從 中央銀 行貨幣政策 的角度 來 看, 取 消準備 率的下限 可使得 貨幣
政策的執行 更具彈 性。基 於 這些因 素 的考慮。及首先 修法取消 準備 率下 限 的
規定 ,

--- chunk 8 (長度 132 字，page_label=2) ---
基 於 這些因 素 的考慮。及首先 修法取消 準備 率下 限 的
規定 , 然 後視經濟金融情 勢, 逐 步調 降準備 率, 以 降低 銀行 經營成本 , 並 逐
步 縮小活期 性與定期 性存款 準備率的 差距 。, 以減少 活期性與定期 性存款 結構
的 扭曲。

--- chunk 9 (長度 177 字，page_label=2) ---
, 以減少 活期性與定期 性存款 結構
的 扭曲。
(二 ) 應提準 備基礎 擴及 新臺幣存款 以外的 負債
以 往中央 銀 行應提準 備規定 僅限於 新臺幣存款 , 外匯 存款則強制 轉存中
央 銀 行與設定 國外負債 限額等方式 進行管理 , 但 這種作法 與先進國家的 管理
慣例 不 合。因 此改 為可對銀行 國外負債 或外匯 存款計提準備 金,

--- chunk 10 (長度 158 字，page_label=2) ---
因 此改 為可對銀行 國外負債 或外匯 存款計提準備 金, 並 與新臺幣
存款 的準備 率及 國 外存款準備 率之間維持平 衡關係 , 不 但符合加入世界 貿易
組 織 (World Trade Organization, WTO) 的規範 。中央 銀 行也具有可 適時因應 短
期 國際 資 本移動的政策 工具 。

--- chunk 11 (長度 141 字，page_label=2) ---
中央 銀 行也具有可 適時因應 短
期 國際 資 本移動的政策 工具 。
根據 「中 央銀 行法」第 二十三條 與「金 融機構存款及其他 各 種負債 準備
金 調整及查核 辦法 」, 現 行準備 金制度 的架構包括 :
(一 ) 提存準備金的機 構、負債 種類與可充當 的資產
1.

--- chunk 12 (長度 37 字，page_label=2) ---
提存 機 構: 本國 一般銀行、外國 銀行在臺分 行、中小企業 銀行、信用

--- chunk 13 (長度 146 字，page_label=3) ---
第四 章 貨幣政策工具 89
合作 社、農 會信用 部、漁 會信用 部 及中華郵政公司 等。
2. 負債 種類 : 支 票存款、活 期存款、儲 蓄存款、定 期存款及其他各 種負債 。
3. 可充當準備 金的資產 主要 包括庫存現金 與在中央 銀 行或受託收管機構
所 開準備 金帳戶 的存款。

--- chunk 14 (長度 190 字，page_label=3) ---
(二 ) 各 類 存款及其他各種負債準備 率的法定上限 分別為支票存款 25%、 活 期
存款 25%、 儲 蓄存款 15%、 定 期存款 15%、 其他 各 種負債 25%。
(三 ) 應提準 備按當 月 各種 存款及其 他各種負債 平均餘額計算。每 月應提的法
定 準備計算 期間為 每月第 一日起至月底止 , 實際 準 備的提存 期間為 每月
第四 日 起至次月第 三日止。

--- chunk 15 (長度 175 字，page_label=3) ---
實際 準 備的提存 期間為 每月
第四 日 起至次月第 三日止。
一 般而 言, 準 備金的提存 制分為當 期 制 (contemporaneous system) 與 落後
制 (lagged system) 兩 種。我 國準備 金制度 的提存 期僅落後計算 期 三日。因 此
仍 可視為當期 制。銀 行在提存 期實際 持有的準備 金為實際準備 ,

--- chunk 16 (長度 148 字，page_label=3) ---
銀 行在提存 期實際 持有的準備 金為實際準備 , 而 依計算期
所算出 應緻存中央 銀 行的準備 金為應提準 備 , 實際 準 備大於 應提準 備的 部分
為 超額 準備。若 超額準備過 多 , 則仰賴 中央銀 行的公開 市場賣出或收受 轉存
款 等方式收回餘裕 資 金。若實際 準備 不 足,

--- chunk 17 (長度 138 字，page_label=3) ---
若實際 準備 不 足, 也有 賴中央 銀 行公開 市場買入債
票 券或以貼現 窗口融通 等方式 , 穩 定資金情勢 ”。 有關 應提準備 的計算 期與
提存 期, 請參閱 圖八。
圖 八 應提 準 備的計算 期與提存 期
應 提 準備 金的計算 期間
應提準 備金的提存 期間

--- chunk 18 (長度 172 字，page_label=4) ---
40 ” 中華民 國中 央銀 行之制度 與功能
(四 ) 金 融機構存於中央 銀行的準備 金按準備 金甲戶 (往來 戶 ) 與準備 金乙戶 ( 計
息 戶 ) 雨 個帳戶 收存。甲 戶的存款 可 隨時 提存。不 計利息。乙 戶為根據
前 一期應提法 定準備 一定成數所 計提 的存款。成 數由中 央銀行 訂定。自
民國 64 年 7 月 起 ,

--- chunk 19 (長度 160 字，page_label=4) ---
成 數由中 央銀行 訂定。自
民國 64 年 7 月 起 , 乙 戶金額一直 為 應提準備 的 609%。90 年 10 月 , 中央
銀行 大幅調降準備 率 , 為避免 甲戶金額過低 , 不利於 銀行 資金 調度 , 乃
於 同年 11 月 起 將乙戶成數降低 為 55%。 金 融機構不 能自由 動用乙 戶次
金 ,

--- chunk 20 (長度 166 字，page_label=4) ---
金 融機構不 能自由 動用乙 戶次
金 , 只有在 發生異常提領 或配合 中央 銀 行貨幣政策 等資金需求 時。才可
以 該帳戶 的餘額 為 質。 申 請融通。由 於金融機 構平時不 能動用 乙戶的 次
金 , 因此 中央 銀 行酚予給 皿。有關銀行 準備金 乙戶利率 的調整。可參考
表 一 。
(五 ) 中央銀行 為調節信用 。

--- chunk 21 (長度 212 字，page_label=4) ---
可參考
表 一 。
(五 ) 中央銀行 為調節信用 。於必要 時可對 支票 存款、活 期存款 與其他各 種負
債 的增加 額。訂定額外準備 金比 率。不 受法定準備 率上限範圍 的限制。
表 一、銀 行準備 金乙戶利率的調整
單位 : 年息百 分 率
64.07.21 2.40%
88.01.07 3.20%
90.10.04 2.50%
92.03.21 1.73%
資料 來源 : 中央 銀行業務 局。
” 依規定 ,

--- chunk 22 (長度 188 字，page_label=4) ---
10.04 2.50%
92.03.21 1.73%
資料 來源 : 中央 銀行業務 局。
” 依規定 , 實際 準 備 的日平均 額如果沒有 達到 應提法 定準備金的日平均 額。不 足額未超過 當期 應提
法 定準備 額 1% 的 部 分, 可申請 以前一期的超額準備 抵充。但 不足額超過 1% 的 部分或未經抵充 的
部 分。按 中央 銀 行無擔保短期 融通 利率 1.

--- chunk 23 (長度 33 字，page_label=4) ---
按 中央 銀 行無擔保短期 融通 利率 1.5 倍計算 追收利息。

--- chunk 24 (長度 164 字，page_label=5) ---
第四 章 _ 貨 幣政策工具
三、 準 備 率的調整
準備 率的調整 為中央 銀行重要的 貨幣政策工具 之 一, 中 央銀行調整 準備
率 , 可改變 準備 金應提的 額度 , 直接 影響銀行可運用資金 的數量以及其信用
創造 過 程。在決定 準備 率調幅 時 , 中 央銀行會先評估收縮 (或 釋出 ) 資 金的
數 量 。,

--- chunk 25 (長度 184 字，page_label=5) ---
中 央銀行會先評估收縮 (或 釋出 ) 資 金的
數 量 。, 及其對 銀行 資金部位的影響。新 臺幣存款應提準 備率在歷經 多次調降
後 , 新 臺幣存款 加權平均應提準備 率已由民國 81 年 的 13.12% 降 至 91 年的
5.07/0。
除了新 臺幣存款準備 率 外, 民 國 89 年 12 月 , 中央 銀 行鑑於當時 銀行外
匯存款 比 重日 增。

--- chunk 26 (長度 124 字，page_label=5) ---
民 國 89 年 12 月 , 中央 銀 行鑑於當時 銀行外
匯存款 比 重日 增。為 兼顧銀行外匯存款 的適當流動 性 , 於 是比照歐元 區、日
本及 新加坡 等金融先進國家對各 種負債提存準備 金的慣例 , 依 法訂定外 匯存
款 準備 率,

--- chunk 27 (長度 174 字，page_label=5) ---
依 法訂定外 匯存
款 準備 率, 並 規定提存基礎 為自 89 年 12 月 8 日 起指定銀行 收受外 匯 活期及 定
期存款 新增部分 ( 含到期 續存 ) 須提存 5% 的準備 金, 存放 於 中央 銀 行的外匯
存款 帳戶。實 施初期 該準備 率訂 為 5%, 其 後配合 經濟金融情勢需要 , 此一
外 匯存 款準備 率也慚經 調整 ,

--- chunk 28 (長度 78 字，page_label=5) ---
此一
外 匯存 款準備 率也慚經 調整 , 至 91 年 6 月 28 日 已降至0.125%。
13.12
12.57
12.00
12 11.30
41

--- chunk 29 (長度 75 字，page_label=6) ---
42 中 華民 國中 央 銀 行之制度與功能
表二 存款及其 他各 種負債準備 金比率的調整
(民國 81 年 至 92 年 6 月 )
單位 :%,

--- chunk 30 (長度 190 字，page_label=6) ---
對存款 額百分比
了 EENE EE 國玉國蟬
以 EE 中 品 吧避上所避 近戰 歡弄加 讓
避 E 太上 9 的 所 讓天加 讓
以還避 苞 的光反光 區玉國 讓
以 太古 避的弄記光 加到加 讓
以克避 序避 呈人 @ 中詢芝 纏加到加 讓
以 友光 單計測噴光 歡天 歡誠
區 本 品攻戰芍 詢螞光點 詢歡天
區 0 克避 的汶 歡 @ 史詢財光 革人 品天
91.06.

--- chunk 31 (長度 147 字，page_label=6) ---
06.28 10.75 9.773 5.30 4.00 3.00 0.125 0
註 : 的 主代入 2 說 還 89 年 12 月8 日 起就指定 銀行收受外匯 活期及定期存款 新增部分 ( 含到期 續存) 提存
資料 來 源: 中央 銀 行 編「中 華民國 臺灣地區 金融統計 月 報 」。

--- chunk 32 (長度 165 字，page_label=7) ---
第四 章 ” 貨 幣政策工具
四 、流 動準備制度
金 融機構應保有隨時可 變現 或者具備 迅速向外借調資金 能力的流動性 資
產 , 以 因應花急 資金需求 , 確 保大眾權益並促進 金融穩定。因此 , 除了針對
銀行 負債的 準備金 制度 外。,「 中 央銀 行法」 與「銀 行法」也 規定中央銀 行 經
洽商 財政 部 後,

--- chunk 33 (長度 163 字，page_label=7) ---
可 規定 銀行流動 資產相對 負債比率的最低標 準。根 據上述 法
源 , 中 央銀 行訂定「金 融機構流動 準備 查核 要點 」, 做 為管理流動 準備 制度
的 依據。
根據 該要點 , 存 款貸幣機構應按支票存款、活 期存款、儲 蓄存 款、定 期
存款 、公庫存 款、金 融業互拆貸差及 票、債 券附買回交易 餘額 等,

--- chunk 34 (長度 158 字，page_label=7) ---
提存 流動
準備 。依 規定可充當 流動準備的 資產 , 包括 超額準備、金 融業互拆借差、
公司 債、金 融債 姜, 及 其他經 中央銀 行核准 的資產。由 於中央 銀 行依法 可 規
定流動 準備 最低標準與資產 種 類, 因 此具有 誘導 銀行 資金運用或授信 的功
能 。, 也 間接具有貨幣政策的影響 力。

--- chunk 35 (長度 180 字，page_label=7) ---
, 也 間接具有貨幣政策的影響 力。
我 國自民國 66 年 7 月開始實施流動 準備制度 , 訂 定法定流動比率為 5%,
67 年提高 為 7%, 實 施至 今。雖 然一般工業化國家 已放棄 法定流動比率的規
定 , 但 我國流動 準備 制度建立以 來, 既有助 於貨幣市場規模的擴大 , 也 使得
金 融機構在因應 流動性短缺方面 , 多了一層 保 障。

--- chunk 36 (長度 148 字，page_label=7) ---
也 使得
金 融機構在因應 流動性短缺方面 , 多了一層 保 障。
第 二節 貼現窗口 制度
一、貼 現窗口 制度 的意義
貼現窗口 制度 為金融機構 向中央銀 行申請各項 融通的機 制。現 行的機制
係 根據「中 央銀 行法」第 十九條及 「中 央銀 行對銀行 辦理融通作業 要點」 運
作 ,

--- chunk 37 (長度 133 字，page_label=7) ---
儿 是在中 央 銀 行設立存款 準備 金帳戶 的銀行。可以經由貼現 窗口向中 央
銀行 申請 融通 , 融 通的方式包括 重貼現、短 期融通 及擔保 放款 之 再融通 , 信
託 投資公司也 準用短期融通 及擔保 放款 再融通 規定。中 央銀 行在金融機 構出
49

--- chunk 38 (長度 178 字，page_label=8) ---
44 中 華民國中 央 銀 行之制度與功能
現 資金短繹時 , 可 透過貼現 窗口 制度 同 還 時 。因而為 金融業者 資金 來
源的 最後貸款者(lender oflast reSsort) 。 項 說 明於 後 :
(一 ) 重 貼現
銀行 可將 持有 的 銀行承兌 匯票、商 業有承兌匯票 或商業本 票 等合格 票據 ,
向中央 銀 行申請重貼現。

--- chunk 39 (長度 161 字，page_label=8) ---
向中央 銀 行申請重貼現。上述 的銀行承兌 匯票、商 業承兌匯 票與商業本 票 等
應 為公民 營生產事業 依據實際 交易 行為而產生。重貼現 期限以票據 的到期 日
為 準, 但工商業票據最長不得超 過九十天 , 農 業票據最長不得超過 一 百八十
天 。重貼現 利息的預扣 , 依 中央銀 行公告 的重貼現 率計 算。

--- chunk 40 (長度 128 字，page_label=8) ---
重貼現 利息的預扣 , 依 中央銀 行公告 的重貼現 率計 算。
隨 著經 濟體系愈趨複 雜 , 認 定各 種 票券是合具有實質交易基礎 也更加還
難 , 而 且也往往 緩不濟 急。因 此 , 在實際運作上銀行較 少以重貼現的方式 向
中 央銀行申請融通。

--- chunk 41 (長度 177 字，page_label=8) ---
因 此 , 在實際運作上銀行較 少以重貼現的方式 向
中 央銀行申請融通。
(二 ) 短 期融通
銀行 須檢 附重貼現 的合格 票據、政 府債 新、 中 央銀 行發行 的定期 存單 或
其 他經 中央銀 行同意 的有價證券 為擔保 品, 申 請短期融通 。, 期 限不能超過十
。 如 果符 合中央銀 行規定 的特殊情 形, 銀 行可 免提供 擔保 品,

--- chunk 42 (長度 156 字，page_label=8) ---
如 果符 合中央銀 行規定 的特殊情 形, 銀 行可 免提供 擔保 品, 但 應檢附在
二條且 : 帳戶內付款的本票。一般而言, 銀行向中央銀行貼現窗口申請 的融通 , 大 多以其所持有的 中央銀 行定期存單 為擔保 , 辦 理有擔保 的 短
期融通 。
在 短期融通 利息的計算方面 , 若提供 合格擔保 品,

--- chunk 43 (長度 159 字，page_label=8) ---
在 短期融通 利息的計算方面 , 若提供 合格擔保 品, 按 融通當 時 中央銀行
公告 的 擔保放款 融通利率計算 ; 若 未提供 合格的擔保 品, 則按 融通當 時中央
銀行公告 的短期 融通利率計算。銀 行申請短期融通的金 額 , 每 月平均不 得超
過當 月 應提存款 準備金 的 10%。 如果 超 逾限額。

--- chunk 44 (長度 150 字，page_label=8) ---
每 月平均不 得超
過當 月 應提存款 準備金 的 10%。 如果 超 逾限額。則逾 限金額的 利息改 按中 央
銀行 公告的 短期融通利率 1.2 倍 計算。銀 行 若連續 兩個月均向中 央 銀 行申請
班 期融通 , 自 第三個月起利息改按中 央 銀 行公告 的短期融通 利率 1.2 倍 計算。

--- chunk 45 (長度 105 字，page_label=9) ---
第四 章 ” 貨 幣政策工具 45
表 三 ” 中 央銀行利率的調整
(民國 81 年 至 92 年 6 月 )
單位 : 年 息百分率
資料 來 源: 中央 銀 行編「中 華民國 臺灣地區 金融統計月報 」。

--- chunk 46 (長度 165 字，page_label=10) ---
46 中 華民國中 央 銀 行之制度與功能
(三 ) 擔 保放款之 再融通
銀行因 承 做政府 核定 並 經中 央 銀行同意 的放款 、或 配合中央銀 行 貨 幣政
策 承做的放款、 或有緊急 性資金需求 並經中央 銀 行同意 者, 可 以中央銀 行同
意 的有價 證券或存款準備 金乙戶為擔保 品, 申 請擔保 放款 之再融通。

--- chunk 47 (長度 178 字，page_label=10) ---
申 請擔保 放款 之再融通。該 項融
通 的期限最長不能超過三百六十天 , 利 息依融通 時中 央 銀 行公告 的擔保 放款
融通利率計算 , 但 若經中央銀 行專案 核准 , 可和酌予 減碼。
二 、中 央銀行貼放利率 的調整
貼 放 利 率係由中央 銀 行訂 定, 具有宣示 的 作用 , 這 類利率也可稱之 為中
央 銀行利率。在 經濟景氣過熱時 ,

--- chunk 48 (長度 180 字，page_label=10) ---
這 類利率也可稱之 為中
央 銀行利率。在 經濟景氣過熱時 , 中 央銀 行可調 高中央 銀 行利率 , 在 景氣不
振 時, 則 可調 降中央 銀 行利率 , 以 對外 界宣示貨 幣政策的取向 , 並引導市 場
利率上升 或下 降。另 一方面。中 央銀 行也 會反映 貨幣市場利率的變動而調整
中 央銀 行利率。自民國 89 年 12 月至92 年 6 月,

--- chunk 49 (長度 173 字，page_label=10) ---
自民國 89 年 12 月至92 年 6 月, 中央 銀 行為刺激經濟景氣 , 調
降 各項中 央 銀 行利率 達十五次之多。有關中 央銀行利率的調整 , 可參閱 表三。
第 三節 ” 公 開 市 場操作
一、公 開 市 場操作 的意義 與目的
公開 市場操作為 中央銀 行經由 金融 市 場, 買 賣票債姜的 方式增減銀行 體
系 的準備 金,

--- chunk 50 (長度 168 字，page_label=10) ---
買 賣票債姜的 方式增減銀行 體
系 的準備 金, 以 調控準備 貨幣與拆款市場利率的操作機 制, 為中央 銀 行最重
要 的貨幣政策工具 。根 據「中 央銀 行法」第二 十 六條的 規定 , 所 買賣的票、
債券包括由 政府 發行或保證的債 狠、央 行 可轉 讓定期存單 、由 銀行 發行的金
融 債券與經銀行承兌 或保證 的票據等。

--- chunk 51 (長度 159 字，page_label=10) ---
中 央銀 行通常視資金 情勢 。靈 活採取公開市場操作 。例如 , 當中 央銀行
為穩定 新臺幣匯率而在外匯市 場買入 (或 賣出) 美 元時 , 銀 行在中 央 銀行的 準
備 金將增加 (或 減少 ), 此 時中央銀行可 賣出 (或 買 進 ) 合格票 據, 使銀行 體系
超 額準備 或準備 貨幣維持在原先水準。

--- chunk 52 (長度 161 字，page_label=11) ---
第四 章 ” 貨 幣政策工具
中 央銀 行實施公開市 場操 作 , 早 期係透過中 興、中 華及 國 際三家 票 券金
融公 司經紀報 價, 民 國 86 年 起改由 金 融機構直接 向中 央 銀 行報價。報 價內
容包括 票券種 類、面 額、首 次發行 價 格、買 賣期 限、操 作 利率 與金額 等。接
受 報價 後,

--- chunk 53 (長度 172 字，page_label=11) ---
接
受 報價 後, 依 據當時資金 狀況與報價情形決定 買賣金 額、方 式、期限及 票 券
種 類, 並通知 金融機構辦理交 割。
為提高公開市場 操作效率 , 中 央銀 行自民國 89 年 1 月 起實施公開 市場操
作 指定交易商 制度 , 凡 與中央 銀 行進行報價的金融機構需具有公開市 場操作
指定交易 商的資格 。92 年 5 月,

--- chunk 54 (長度 203 字，page_label=11) ---
92 年 5 月, 中 央銀 行將「公開 市場操作指定交易 商管理
要 點」 修 正為「公開 市場操作 指定交易 商實施要點 」, 擴 大指定交易 商的範
圍 , 增 納證券公司 為公開 市場操作對 象, 以 建立中 央公 債主要 交易 商制度。
該 實施要點自 6 月16 日 起實施。此外 , 為 縮短公開 市場操作的作業 時間 , 中
央 銀行也自92 年 4 月28 日起修正公開 市場操作方 式,

--- chunk 55 (長度 134 字，page_label=11) ---
中
央 銀行也自92 年 4 月28 日起修正公開 市場操作方 式, 由以 往的人工投標 改為
網 路連線 系統的線上自動 化作業 方式。
二 、公 開市 場 操作的 方式
公開 市場操作的 方式包含 買 ( 賣 ) 斷 交易、 附 買 ( 賣 ) 回 協定等方式 。

--- chunk 56 (長度 172 字，page_label=11) ---
( 賣) 斷交易
) 蝦
(一
中 央銀 行可向 金融機構買斷 ( 賣 斷) 短 期票 疤、政 府債狠及中 央 銀 行可 轉
讓定期 存單。若 預估人資金 緊償 或寬鬆 狀況 期間較 長 , 可 採 此一交易 方式。
(二 ) 附 買 ( 賣 ) 回 協定
附 買 ( 賣 ) 回協定 係中央銀 行在向金融機構買入 (或 賣出) 債 票疤時 ,

--- chunk 57 (長度 151 字，page_label=11) ---
約 定
於 未來某 一日期由 中 央銀 行按約 定價格重新 賣出 (或 買 入 ) 該 債票 姜。若 市場
上 資金的鬆緊 狀況為短期 現象時 , 可 採取 此一操作 方式。例 如 , 每 月月底 或
月 初例行 性資金需求較 高 時 , 銀 行體系 資金較為 緊們 , 中 央銀 行可運用 附買
47

--- chunk 58 (長度 159 字，page_label=12) ---
48 中 華民國中 央 銀 行之制度與功能
回 協定 , 買 入銀行 持
有 的政府 債 姜, 而 於
中通貨 回籠時 , 賣
回 該債姜 收回新臺幣
資金 。中 央銀 行在民
國 2 年 6 月 首 度實施
附 買回操作 , 由 於 該
項操作 較 具 彈性 , 成
為中央 銀行調節新 臺
幣 資金的 重要方式 。

--- chunk 59 (長度 120 字，page_label=12) ---
成
為中央 銀行調節新 臺
幣 資金的 重要方式 。
公開 市場操作
三、發 行中央銀 行票 券
我 國因進 出口貿易持續 出 超, 銀 行體系資金 較為 充裕 , 為避免 市場資金
過 於浮濫 , 中 央銀 行經常須和 行村基因收半合 。

--- chunk 60 (長度 174 字，page_label=12) ---
中 央銀 行經常須和 行村基因收半合 。因 此廣義 的中央銀 行公開市
場 操作也包括 中央銀 行發行的各 種 票
(一 ) 中央 銀行定期存單
根據 「中 央銀 行法」第 二十七條 , 中 央銀 行可以本 身 為債務人對 金融機
構 發行央行定期 存單 , 藉 此回收銀 行體系 過剩 資 金。反 之 , 假 如中 央 銀 行希
望放寬信用時 ,

--- chunk 61 (長度 190 字，page_label=12) ---
反 之 , 假 如中 央 銀 行希
望放寬信用時 , 則 可以買斷或附買回方式 購入以 往發行的上述 工具 , 以 釋出
中 央銀 行定期 存單 (以 下簡稱央行定期 存單 ) 發 行及持有對 象為銀行、信
託 投資 公司、票 券金融公 司、 中華 郵政公司 及其他經中 央 銀 行核可的 金融 機
構。店 、1,000 萬 元、 與 1 億 元等三種。
在 發行的形式 方面 ,

--- chunk 62 (長度 139 字，page_label=12) ---
店 、1,000 萬 元、 與 1 億 元等三種。
在 發行的形式 方面 , 分 為實體與無實體發行兩 種, 後 者於民國 80 年 10 月 起
即已開始實施。自此以後 , 不再發行實體定存單。
在定期 存單 的種類方面。最 早分為 三、六 、九 個月與 一、二 、三 年期。

--- chunk 63 (長度 168 字，page_label=13) ---
第四 章 ” 貨 幣政策工具
民國 88 年 6 月修正 「中 央銀 行發行定期 存單要點 」, 發 行十四天及二十八天
期定期 存單。係 採申購 ( 非 競標 ) 方 式。由 於 係由中 央銀 行訂定利率 並決定 發
行 金 額 。, 因 此外 界也得 以該兩類存單 的利率 與金額為參考 指標。觀 察中央 銀
行貨幣政策的 動向 。

--- chunk 64 (長度 185 字，page_label=13) ---
觀 察中央 銀
行貨幣政策的 動向 。
民國 89 年 2 月再度修正「中 央銀 行發行定期 存單要點 」, 除了上述十四
天 與二十八天 期 限別以外 , 中 央銀 行也採取定期 標售方式 發行較 長天 期 的定
期 存單 , 發 行天期包括九十 一天 期、一 百八十二天期、三 百六十四天期及 兩
年 期 等 。, 有助 於中央銀 行瞭解市場動 向。標 售完畢 後。

--- chunk 65 (長度 192 字，page_label=13) ---
, 有助 於中央銀 行瞭解市場動 向。標 售完畢 後。依 得標的加權 平均利
率 酌予加減 碼, 做 為申購同天期 定期存單 的利率。
由 於央行定期 存單具有各 種期 別。 中 央銀 行的公開 市場操作更 為靈活 ,
可 使各存單 到 期的沙點女 善分 布。有助 於金融穩 定。此外 , 中 央銀 行於必要
時 也可 以 發行特定期限 (即 不屬於上述 期 限 ) 的定期 存單 ,

--- chunk 66 (長度 200 字，page_label=13) ---
中 央銀 行於必要
時 也可 以 發行特定期限 (即 不屬於上述 期 限 ) 的定期 存單 , 以增加 操作彈性 ,
適時因應 市場變 化。例 如在 新舊曆年關之 前, 中 央銀 行對於定期存單 的發行
都妥善 安排到期 日的沙點 , 以便利 銀行調度 資金。
央行定期存單 於民國 88 年 起迅速增加 , 至 92 年 6 月底的 餘額已 超過兩兆
元 , 為 中央銀 行實施公開 市場操作中 ,

--- chunk 67 (長度 177 字，page_label=13) ---
為 中央銀 行實施公開 市場操作中 , 運用 最 為頻繁 的政策 工具 。
(二 ) 國庫 券與中央銀 行儲蓄 券
以 往中 央 銀 行曾以調節 金融為 目的發行 國庫 姜。 以 吸收市場過剩 的 流動
性 , 但 自民國 87 年 7 月「短 期借款 暨國庫六 發 行條例」實 施 後, 中 央銀 行已
不 得發行國庫券。
在 中央銀 行儲蓄券方面 ,

--- chunk 68 (長度 142 字，page_label=13) ---
中 央銀 行已
不 得發行國庫券。
在 中央銀 行儲蓄券方面 , 發 行對象 主要為 一般社會大 眾, 但 金融機構也
可 申購 , 因 此 兼具控 制銀行 準備 部 位與吸收社會 游資的雙重 功能。惟 該儲蓄
券 至民國 81 年 1 月 全部到期 兌償完畢 , 此 後 未再發行。

--- chunk 69 (長度 66 字，page_label=13) ---
此 後 未再發行。
第 四節 ” 金 融機構轉存款
中 央銀行可視 經濟金融情勢的需要 , 接 受金融機構所吸收存款 的轉存。
49

--- chunk 70 (長度 128 字，page_label=14) ---
50 中 華民國中 央 銀 行之制度與功能
此 一轉存包含 郵政 儲金轉存款及銀行 轉存款 等兩個部 分。兩 者的歷史 皆由來
已 久 , 其 間為因應 經濟金融環境 的變遷 而歷經 多次修改 , 可參閱 前版的「中
華民 國 中央銀 行之制度 與功能」。

--- chunk 71 (長度 178 字，page_label=14) ---
可參閱 前版的「中
華民 國 中央銀 行之制度 與功能」。茲 就現行轉存制度說 明 於和后 :
郵政 儲金轉存制度由最 早期民國 53 年 的全部 轉存中央銀 行做為中長 期
資金 用途 , 民 國70 年 代轉 存中央 銀 行與交通 銀行、臺 灣土地銀行、臺 灣中
小企業 銀行、中國農民 銀行 等四家 專業 銀行 , 演 變至81 年 1 月 以 後,

--- chunk 72 (長度 170 字，page_label=14) ---
演 變至81 年 1 月 以 後, 為增加
郵政 儲 金自行運用 的 彈性 , 新 增郵政 儲金可 自由 轉 存各銀行並購買公債 、
庫 券、中 央銀 行發行的單券及金 融債 券。86 年 12 月 起可購買經中央銀 行、
財政 部與交通 部共同 研商決定 可投資 的 債、票 券。
銀行 的轉存制度也有一 段歷史 ,75 年 3 月 起,

--- chunk 73 (長度 153 字，page_label=14) ---
銀行 的轉存制度也有一 段歷史 ,75 年 3 月 起, 中 央銀行視經濟金融情勢
的 需要 , 機 動訂定轉存額度。收 受銀行 的轉存款 。, 期 限最長不超過 一 年。可
轉 存對象包括收受基層 金 融機構存款 的農業 銀行 , 以及 經中 央銀 行專案 核准
的 銀行。
雖然轉存 制度 有所改變 ,

--- chunk 74 (長度 151 字，page_label=14) ---
以及 經中 央銀 行專案 核准
的 銀行。
雖然轉存 制度 有所改變 , 金 融機構轉存款 仍為中央銀 行穩定 金融的重要
貨 幣政策 工具。
第 五節 選擇 性信用 管理
選擇 性信用 管理包括選擇 性信用 融通 與選擇 性信用 管制。
一、選 擇性信用 融通
選擇 性信用 融通可分 為兩個部 分。

--- chunk 75 (長度 145 字，page_label=14) ---
一、選 擇性信用 融通
選擇 性信用 融通可分 為兩個部 分。一 為中央 銀行基於 特定 的經濟發 展目
的 。, 以郵政 儲金轉存款 為資金融通 來 源, 由 金融機 構申請核 撥, 以配合 政策
性 放款 , 形 同寬鬆 的貨幣政策 ; 另 一為中央 銀 行本身不提供融通資金 來源 ,

--- chunk 76 (長度 114 字，page_label=14) ---
形 同寬鬆 的貨幣政策 ; 另 一為中央 銀 行本身不提供融通資金 來源 ,
但 與其他有關 部 會合作推 動並督促 金融機構辦理各項 專案貸款 , 以 促進經濟
發 展。
(一 ) 以郵政 儲金轉存款為 資金來 源融通金融機構

--- chunk 77 (長度 166 字，page_label=15) ---
第四 章 ” 貨 幣政策工具
1. 九 二一地 震災 民 重建家 園 緊急融資 : 依 據民 國 88 年 9 月總 統發布的
緊急 命令 , 提 撥 專款供各指定 金融機構辦理災民 重建家 園 所需長期低
利 緊急融資。另 根據「九二 一 震災 重建暫行條 例 」, 對 於 願意承受災
民 震災毀 損房屋及 土地的 金融機 構,

--- chunk 78 (長度 158 字，page_label=15) ---
對 於 願意承受災
民 震災毀 損房屋及 土地的 金融機 構, 中央 銀 行於專案融資 額度 內提供
利息 補助 。, 以促進 金融機 構的承受意願 ; 上 此外, 中 央銀 行也對 災民原
先 向金融機 構的房屋 借款 , 以 每戶最高 350 萬 元額度 內提供利息補
貼 , 以 減輕災民 的利息負擔 。
2.

--- chunk 79 (長度 173 字，page_label=15) ---
以 減輕災民 的利息負擔 。
2. 協助 九二一及一 0 二 二地 震受災 公 私立 學 校、醫 事機 構、宗 教寺廟 、
歷史建築 的復 建: 中 央銀 行分別針對上 述 機構提撥 100 億 元、50 依
元 、20 億 元與 10 億 元供指定 銀行 辦理 各項 重建及修復 貸款。此外 。,
為 協助林肯 大和鄧 全毀受災戶購置 住宅 ,

--- chunk 80 (長度 181 字，page_label=15) ---
此外 。,
為 協助林肯 大和鄧 全毀受災戶購置 住宅 , 中 央銀 行也提撥 7 億 元供內政
部指定 的銀行辦理 專案貸款 。
3. 中小企業購置 機器設備 或週轉金貸款專案 融通 : 自民國 87 年 11 月 起
中 央銀 行提撥 郵政 儲金轉存款 300 億 元, 供本 國 銀行辦理中小企業 及
生 產企業 購置 機器設備 或週轉金貸款 之用。
4.

--- chunk 81 (長度 187 字，page_label=15) ---
無 自用住宅民眾 首次購屋 貸款 : 由 於 房地產 景氣低迷 , 而 銀行放款又
以 房地產擔保 為 主, 為 維持 金融穩 定, 中 央銀 行 於民國 84 年 11 月提
撥 1,000 億 元, 供 銀行 辦理 無自用住宅民眾 首次購屋 貸款。該 項貸款
推 出 後, 民 眾申貸十分踴躍 , 半年後即撥貸完 畢。此外 , 中 央銀 行也
另 提撥 150 億 元,

--- chunk 82 (長度 164 字，page_label=15) ---
半年後即撥貸完 畢。此外 , 中 央銀 行也
另 提撥 150 億 元, 供 銀行對正當 經 營的建築業辦 理建築週轉融資 , 至
85 年 11 月截止 。
鑑於 前述購屋 貸款專案 成 效良 好, 民 國 87 年 8 月 中央 銀 行再度
撥款 300 億 元, 供 銀行 辦理 無自用住宅民眾 首次購屋 低利貸款融資 。

--- chunk 83 (長度 174 字，page_label=15) ---
供 銀行 辦理 無自用住宅民眾 首次購屋 低利貸款融資 。
88 年 1 月配合 行政 院「提 振 建築投資 業措施 」, 中 央銀 行八提撥 1,500
億 元供銀行 辦理購屋 貸款 , 其 中 600 億 元為 無自用住宅專案 貸款 ,
898 億 元 為購置 新屋 專案融 資。2 億 元 為 無自 用住宅 原住民 購屋 專案
融資 。
51

--- chunk 84 (長度 56 字，page_label=16) ---
52 中 華民國中 央 銀 行之制度與功能
(二 ) 與財政 部、內 政部合作 推 動金融機構辦理專案貸款
1.

--- chunk 85 (長度 171 字，page_label=16) ---
優惠購屋 專案 貸款 : 依據行政院 於民國 89 年 至 92 年各年 的核定 , 中
央 銀行會同財政 部 與內政部推 動並督促金融機構辦理總額達 1.2 兆元
旨 惠購屋專案 貸款 , 對 於民眾或青年購置 住宅由 內 政部提供貸款 利息
補貼 , 其中 青年優惠房貸 並有信用 保證機 制, 不必 籌 足自備款即可購
置 住宅。
2.

--- chunk 86 (長度 165 字，page_label=16) ---
傳統產業 專案貸款 暨信用 保證 專案 : 依據民國 89 年 10 月行 政院財經
小組 擴大 會議結論 , 中 央銀 行與財政 部共同 辦理總額達 1.4 兆 元傳統
產業 專案貸款 暨信用 保證專案 , 針 對傳統產業提供 短、中期 週轉融資
及 資本性支出 融資。如 果企業 廠商擔保品不 足, 可 以信用 保證 借款 ,

--- chunk 87 (長度 159 字，page_label=16) ---
如 果企業 廠商擔保品不 足, 可 以信用 保證 借款 ,
保證 成數最高為貸款額度 的八 成。發 款 利率也十分優惠 , 以 協助傳統
產業取得 營運 資金。
二 、選 擇 性信用 管制
選擇 性信用 管制係指對金 融機構某些業務採 取限 制措施 , 以控制 資金 的
流向 與流量 , 達 成特定的經濟金融目 標。

--- chunk 88 (長度 147 字，page_label=16) ---
以控制 資金 的
流向 與流量 , 達 成特定的經濟金融目 標。選 擇 性信用 管制的直接 影響不在於
銀行 的準備 部 位, 而 係透過 對特 定的銀行放款業務 項目 與量的限制。以 抑制
投機性的資金 需求 , 進 而穩定 金融。根 據現行「中 央銀 行法」 與「銀 行法」
等 的規定 ,

--- chunk 89 (長度 118 字，page_label=16) ---
根 據現行「中 央銀 行法」 與「銀 行法」
等 的規定 , 中 央銀 行可採 行的選擇 性信用 管制措施包括 不動產信用 管制、消
費 者信用 管制、直 接 信用管制與貸放比率 的限制 等。
在實際 執行選擇 性信用 管制政策 方面。

--- chunk 90 (長度 160 字，page_label=16) ---
在實際 執行選擇 性信用 管制政策 方面。中 央銀 行曾於 民國 78 年 3 月對金
融 機構辦理購地、土地擔保 等放款 及對投資公司授信 訂定 最 高貸款限額 與期
限 的規定 , 以 抑制銀行 信用的過 度擴張 , 俾促進 金融穩定及健全 銀行業務 經
營。可 以視為直接信用 管制與不動產信用 管制的混合 運用。

--- chunk 91 (長度 130 字，page_label=16) ---
可 以視為直接信用 管制與不動產信用 管制的混合 運用。該 項措施 已於 85
年中 止。
綜合 上 述, 中央 銀 行貨幣政策工具包括 準備 金制度、貼 現窗口 制度、公
開 市場操作、金 融機構轉存款及 選擇 性信用 管理 等。此外 , 中 央銀 行於必要

--- chunk 92 (長度 177 字，page_label=17) ---
第四 章 ” 貨 幣政策工具
時對 銀行業者 進行勸說 , 要 求業者限制 業務量 或採取配合 措施 , 以 達成政策
目標 , 並強化 原有 貨 幣政策的效力 , 這 種方式 稱為道義 說 服。道 義說服包含
不 同的形式 , 通 常是以電話 或非正式會議的方式 與業者 溝通。此 外 , 中央銀
行對外公開 說明 政策 取向 , 以爭取 各界支持 ,

--- chunk 93 (長度 178 字，page_label=17) ---
此 外 , 中央銀
行對外公開 說明 政策 取向 , 以爭取 各界支持 , 使 經濟金融情勢 朝向預期 目
標 , 可視 為廣義 的道德說 服。
為 強化貨幣政策的傳遞 效果 , 中 央銀 行自民國 90 年下半年起積極 鼓勵
銀行 採行指數 型房屋 貸款及 改革 基本 放款利率 制度。指 數型房貸 以指標利率
加 計固 定加碼 做為房貸 計價 利率 ,

--- chunk 94 (長度 169 字，page_label=17) ---
指 數型房貸 以指標利率
加 計固 定加碼 做為房貸 計價 利率 , 具有資訊 透明、隨 市場利率 彈性調整 等特
性。此外 , 房 貸戶也可 以增補契約 的方式 將舊有房貸 轉 換為指數 型房貸 , 在
市 場利率趨跌時 , 能 與新房貸 戶同時享有房貸 利率下跌 的好處。另 一方面 ,
鑑於 銀行基本 放款利率 調整 過於 僵化 ,

--- chunk 95 (長度 139 字，page_label=17) ---
另 一方面 ,
鑑於 銀行基本 放款利率 調整 過於 僵化 , 中 央銀 行也促請 銀行公會 參考 美國、
英國 等先進國家研究放款訂價 方式 , 以改革基本 放款利率 制度。銀 行已自91
年 8 月 起陸續選取 市 場指標利率 , 並 將其基準利率 與指標利率 連動。
59

--- chunk 96 (長度 23 字，page_label=18) ---
54 ” 中華民國 中 央 銀 行之制度與功能

## `embedding_service.py`
* 專心處理 embedding
* 可呼叫轉換成 embedding 向量的 mapping

In [ ]:
%%writefile RAG_module/embedding_service.py
import os
os.environ["HF_HOME"] = "/content/drive/MyDrive/hf_cache"
from sentence_transformers import SentenceTransformer
# from llama_index.core import Settings
# from google import genai
# import RAG_module.api


# _client = genai.Client()
_model = None


def _get_model(embedding_model):
  global _model
  if _model is None:
    print(f"載入本地 embedding 模型：{embedding_model}（第一次執行需要下載模型檔案，請稍候）")
    _model = SentenceTransformer(embedding_model)
  return _model


def create_document_embedding(text, embedding_model):
  model = _get_model(embedding_model)
  return model.encode(text, normalize_embeddings = True).tolist()

  #result = _client.models.embed_content(model = embedding_model,
  #                                      contents = text,
  #                                      config = {'task_type': "RETRIEVAL_DOCUMENT"})

  #return result.embeddings[0].values


def create_query_embedding(text, embedding_model):
  model = _get_model(embedding_model)
  return model.encode(text, normalize_embeddings = True).tolist()

  #result = _client.models.embed_content(model = embedding_model,
  #                                      contents = text,
  #                                      config = {"task_type": "RETRIEVAL_QUERY"})


  #return result.embeddings[0].values

Writing RAG_module/embedding_service.py

In [ ]:
## check if the embedding model should be re-downloaded
import subprocess
result = subprocess.run(
    ["ls", "-lh", "/content/drive/MyDrive/hf_cache/hub/models--BAAI--bge-m3/blobs/"],
    capture_output=True, text=True
)
print(result.stdout)

total 4.3G
-rw------- 1 root root   54 Jul 18 01:27 0140ba1eac83a3c9b857d64baba91969d988624b
-rw------- 1 root root  123 Jul 18 01:27 1fba91c78a6c8e17227058ab6d4d3acb5d8630a9
-rw------- 1 root root  17M Jul 18 01:28 21106b6d7dab2952c1d496fb21d5dc9db75c28ed361a05f5020bbba27810dd08
-rw------- 1 root root  349 Jul 18 01:27 952a9b81c0bfd99800fabf352f69c7ccd46c5e43
-rw------- 1 root root 2.2G Jul 18 01:28 993b2248881724788dcab8c644a91dfd63584b6e5604ff2037cb5541e1e38e7e
-rw------- 1 root root  191 Jul 18 01:28 9bd85925f325e25246d94c4918dc02ab98f2a1b7
-rw------- 1 root root  964 Jul 18 01:28 b1879d702821e753ffe4245048eee415d54a9385
-rw------- 1 root root 2.2G Jul 18 01:28 b5e0ce3470abf5ef3831aa1bd5553b486803e83251590ab7ff35a117cf6aad38
-rw------- 1 root root 4.9M Jul 18 01:28 cfc8146abe2a0488e9e2a0c56de7952f7c11ab059eca145a0a727afce0db2865
-rw------- 1 root root  444 Jul 18 01:28 dc69ac559dcba2694012009aaa108c614541789a
-rw------- 1 root root  16K Jul 18 01:27 e5a320176edd6ee1cfb256e68ee5ac0004de9447
-rw------- 1 root root  687 Jul 18 01:27 e6eda1c72da8f9dc30fdd9b69c73d35af3b7a7ad

## `vector_store.py`

* 創建向量資料庫連線層

In [ ]:
%%writefile RAG_module/vector_store.py
from qdrant_client import (
    QdrantClient
)

def create_vector_store():
  return QdrantClient(path = "RAG_module/qdrant_db")

Writing RAG_module/vector_store.py

## `qdrant_repository.py`
* 專心處理 Qdrant
* 負責所有與 Qdrant Point/Collection 有關的操作

In [ ]:
%%writefile RAG_module/qdrant_repository.py
from qdrant_client import QdrantClient
from qdrant_client.models import (
    PointStruct,
    VectorParams,
    Distance,
    Filter,
    FieldCondition,
    MatchValue
)

# 建立一個 qdrant collection
def create_collection(client,
                      collection_name,
                      vector_size):
  if client.collection_exists(collection_name):
    client.delete_collection(collection_name)

  client.create_collection(collection_name = collection_name,
                           vectors_config = VectorParams(size = vector_size,
                                                         distance = Distance.COSINE))


# 檢查 collection是否已經存在
def collection_exists(client, collection_name):
  return client.collection_exists(collection_name)


def create_point(idx,
                 text,
                 embedding,
                 metadata):
  payload = {"text": text}
  payload.update(metadata)
  return PointStruct(id = idx,
                     vector = embedding,
                     payload = payload)

# create a list of points from a list of nodes
def create_points(nodes, create_embedding, embedding_model):
  points = []

  for idx, node in enumerate(nodes):
    embedding = create_embedding(node.text, embedding_model)
    point = create_point(idx,
                         node.text,
                         embedding,
                         node.metadata)
    points.append(point)

  return points

# client 是程式與資料庫溝通的媒介
# 將一批 Points 寫入指定的 Collection
def upsert_points(client, collection_name, points):
  # 將資料送入資料庫
  client.upsert(collection_name = collection_name,
                points = points)

def search_points(client,
                  collection_name,
                  query_vector,
                  limit = 3,
                  filters = None):
  return client.query_points(collection_name = collection_name,
                             query = query_vector,
                             limit = limit,
                             query_filter = filters,
                             with_payload = True)

def build_metadata_filter(metadata_filters):
  if not metadata_filters:
    return None

  conditions = [FieldCondition(key = k,
                               match = MatchValue(value = v)) for k, v in metadata_filters.items()]
  return Filter(must = conditions)

Writing RAG_module/qdrant_repository.py

## `bm25_retriever.py`
* 負責 sparse search 內涵

In [ ]:
%%writefile RAG_module/bm25_retriever.py
from rank_bm25 import BM25Okapi
import jieba
import RAG_module.api

_DOMAIN_TERMS = [
    # 支付清算類
    "跨行金融資訊系統",
    "票據交換結算系統",
    "信用卡結算系統",
    "外幣結算平台",
    "中央登錄債券系統",
    "債券等殖成交系統",
    "證券劃撥結算系統",
    "票保結算系統",
    "財金公司",
    "聯卡中心",
    "集保結算所",
    "櫃買中心",
    "即時總額清算",
    "定時淨額清算",
    "混合清算",
    "款對款同步收付",
    "款券同步交割",
    "系統性風險",
    "清算風險",
    "日間透支",
    # 貨幣政策工具類
    "準備金制度",
    "貼現窗口",
    "公開市場操作",
    "選擇性信用管理",
    "短期融通",
    "擔保放款之再融通",
    "金融機構轉存款",
    "選擇性信用融通",
    "選擇性信用管制",
    "附買回協定",
    "附賣回協定",
    "中央銀行定期存單",
    "中央銀行儲蓄券",
    "不動產信用管制",
    "消費者信用管制",
    # 氣候金融類
    "氣候變遷風險",
    "有形風險",
    "轉型風險",
    "總體審慎",
    "永續投資",
    "責任投資",
    "壓力測試",
    "淨零轉型",
    "綠色金融行動方案",
    "外匯存底管理",
    # 央行比較法制類
    "中央銀行法",
    "理事會",
    "貨幣政策委員會",
    "法定資本",
    "準備銀行法",
    # 國際組織/機構類
    "國際清算銀行",
    "金融穩定委員會",
    "巴塞爾銀行監理委員會",
    "綠色金融體系網絡",
]

for _term in _DOMAIN_TERMS:
  jieba.add_word(_term)


def _tokenize(text):
  return list(jieba.cut(text.lower()))


def _matches_filters(node, metadata_filters):
  return all(node.metadata.get(k) == v for k, v in metadata_filters.items())


class BM25Retriever:
  def __init__(self, nodes):
    self.nodes = nodes
    tokenized = [_tokenize(node.text) for node in nodes]
    #tokenized = [node.text.lower().split() for node in nodes]
    # 建一個能快速查關鍵字的索引
    self.bm25 = BM25Okapi(tokenized)

  def retrieve(self, query, limit = 3, metadata_filters = None):
    tokenized_query = _tokenize(query)
    # tokenized_query = query.lower().split()
    scores = self.bm25.get_scores(tokenized_query)

    if metadata_filters:
      for i, node in enumerate(self.nodes):
        if not _matches_filters(node, metadata_filters):
          scores[i] = -1

    top_indices = sorted(range(len(scores)),
                         key = lambda i: scores[i],
                         reverse = True)[:limit]

    return [(self.nodes[i], scores[i]) for i in top_indices]

Writing RAG_module/bm25_retriever.py

In [ ]:
## test: 確認 bm25_retriever.py 裡新的 _DOMAIN_TERMS 是否讓 jieba 不再切散這些詞
import jieba
import RAG_module.bm25_retriever as bm25_retriever

print(f"已載入 {len(bm25_retriever._DOMAIN_TERMS)} 個領域詞彙\n")

broken_terms = []
for term in bm25_retriever._DOMAIN_TERMS:
  segmented = list(jieba.cut(term))
  if len(segmented) > 1:
    broken_terms.append((term, segmented))

if broken_terms:
  print(f"=== 載入後仍被切散的詞彙（共 {len(broken_terms)} 個） ===")
  for term, segmented in broken_terms:
    print(f"{term}  ->  {' / '.join(segmented)}")
else:
  print(f"全部 {len(bm25_retriever._DOMAIN_TERMS)} 個詞彙都不再被切散，載入生效。")

/usr/local/lib/python3.12/dist-packages/jieba/__init__.py:44: SyntaxWarning: invalid escape sequence '\.'
  re_han_default = re.compile("([\u4E00-\u9FD5a-zA-Z0-9+#&\._%\-]+)", re.U)
/usr/local/lib/python3.12/dist-packages/jieba/__init__.py:46: SyntaxWarning: invalid escape sequence '\s'
  re_skip_default = re.compile("(\r\n|\s)", re.U)
/usr/local/lib/python3.12/dist-packages/jieba/finalseg/__init__.py:78: SyntaxWarning: invalid escape sequence '\.'
  re_skip = re.compile("([a-zA-Z0-9]+(?:\.\d+)?%?)")
/usr/local/lib/python3.12/dist-packages/jieba/_compat.py:18: UserWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html. The pkg_resources package is slated for removal as early as 2025-11-30. Refrain from using this package or pin to Setuptools<81.
  import pkg_resources
Building prefix dict from the default dictionary ...
DEBUG:jieba:Building prefix dict from the default dictionary ...
Dumping model to file cache /tmp/jieba.cache
DEBUG:jieba:Dumping model to file cache /tmp/jieba.cache
Loading model cost 0.632 seconds.
DEBUG:jieba:Loading model cost 0.632 seconds.
Prefix dict has been built successfully.
DEBUG:jieba:Prefix dict has been built successfully.

已載入 54 個領域詞彙

全部 54 個詞彙都不再被切散，載入生效。

## `reranker.py`
* 負責 reranking
* 為了溯源引用，輸入輸出都必須更改資料型態，不能再是純文字了，這是這模組最大的更動。

In [ ]:
%%writefile RAG_module/reranker.py
from sentence_transformers import CrossEncoder

class Reranker:
  def __init__(self, model_name):
    self.model = CrossEncoder(model_name)

  def rerank(self, query, chunks, top_k):
    pairs = [(query, chunk["text"]) for chunk in chunks]
    scores = self.model.predict(pairs)
    ranked = sorted(zip(chunks, scores),
                    key = lambda x: x[1],
                    reverse = True)
    reranked = []
    for chunk, score in ranked[:top_k]:
      chunk = dict(chunk)
      chunk["rerank_score"] = float(score)
      reranked.append(chunk)
    return reranked

Writing RAG_module/reranker.py

## `prompt_builder.py`
* 建立 augmented prompt

In [ ]:
%%writefile RAG_module/prompt_builder.py
def _format_location(chunk):
  location = chunk.get("file_name") or "未知來源"
  if chunk.get("page_label"):
    location += f" 第{chunk['page_label']}頁"
  return location


def build_prompt(query, chunks):
  citation_map = {}
  context_blocks = []

  for i, chunk in enumerate(chunks, start = 1):
    tag = f"S{i}"
    citation_map[tag] = {
        "file_name": chunk.get("file_name"),
        "page_label": chunk.get("page_label"),
        "text": chunk.get("text")
    }
    context_blocks.append(f"[{tag}] ({_format_location(chunk)})\n{chunk.get('text', '')}")

  context = "\n\n".join(context_blocks)
  available_tags = ", ".join(citation_map.keys()) if citation_map else "none"

  prompt = f"""You are a RAG assistant that must cite sources.
  Answer the question only according to the context below.
  Each context block starts with a source tag like [S1], [S2].

  Rules:
  - Before answering, check whether the context actually identifies the
    specific country/institution/regulation named in the question. If the
    context does not explicitly establish that it is about that subject, say
    exactly: "I don't know." Do NOT assume unlabeled provisions belong to the
    country or institution asked about just because the surrounding structure
    or topic (e.g. "board composition", "capital requirements") matches. This
    matters especially for the comparative central bank law documents, which
    cover many countries with parallel article structures (e.g. Israel, South
    Africa, Indonesia, Turkey, Bahamas, USA) — a matching section heading does
    NOT mean it is about the country asked about.
  - When the context contains a figure (e.g. a rate, ratio, amount) that
    changed multiple times over a time series (e.g. reserve ratio or discount
    rate adjustment history), first check whether the question specifies a
    particular date or period:
      - If a specific date/period is named in the question, use the value
        that was in effect at that date/period, not the latest value.
      - If no date is specified (e.g. the question asks for the "current" or
        unqualified value), use the LAST/FINAL value in the time series
        across all context blocks, and briefly verify no later context block
        revises it further.
  - If the answer is not found in the context, say exactly: "I don't know."
  - For every factual claim in your answer, immediately add the source tag(s)
    it is based on, e.g. "...as stated in the report [S2]."
  - Only use tags that literally appear in the context below ({available_tags}).
    Never invent a tag or cite something not present in the context.
  - When there are more than one answer, use more context information to select
    and propose the best answer.

  Context: {context}
  Question: {query}
  Answer:"""

  return prompt, citation_map

Writing RAG_module/prompt_builder.py

## `gemini_client.py`
* 涉及與 LLM 模型服務的互動
* 使用 Grok 或 Gemini

In [ ]:
%%writefile RAG_module/gemini_client.py
import time
from google import genai
from groq import Groq, RateLimitError
import RAG_module.api


def setup_gemini():
  # use Google gemini
  # return genai.Client()
  return Groq()


def ask_gemini(client, prompt, llm_model, max_retries = 5):
  # 延遲避免 resource exhausted
  # time.sleep(1)

  # use Google gemini
  # response = (
  #    client.models.generate_content(model = LLM_MODEL,
  #                                   contents = prompt)
  #)
  # return response.text
  for attempt in range(max_retries):
    try:
      response = client.chat.completions.create(
          model = llm_model,
          messages = [{"role": "user", "content": prompt}]
      )
      return response.choices[0].message.content

    except RateLimitError as e:
      if attempt == max_retries - 1:
        raise

      wait_seconds = 2 ** (attempt + 1)
      print(f"{attempt + 1}/{max_retries}: [LLM] encounters rate limit, wait for {wait_seconds} seconds to retry...")
      time.sleep(wait_seconds)

Writing RAG_module/gemini_client.py

## `retrieval_pipeline.py`
* retrieval 在做以下事情時蠻容易大量重複，所以做成一個 pipeline 讓程式碼更加簡潔
> * 將 query 轉換成向量
> * 進行 dense search 或者 關鍵字詞搜尋
>> * 若要執行 metadata filtering 的話，在這裡做
> * 將上述的搜尋結果合併
> * 進行 rerank 取出前幾名

In [ ]:
%%writefile RAG_module/retrieval_pipeline.py
from RAG_module.embedding_service import create_query_embedding
from RAG_module.qdrant_repository import search_points, build_metadata_filter
from RAG_module.config import COLLECTION_NAME


def _make_chunk(text, metadata, score = None):
  return {
      "text": text,
      "file_name": metadata.get("file_name"),
      "page_label": metadata.get("page_label"),  # None if the file is .txt
      "score": score,
  }


def run_retrieval(qdrant_client, bm25_retriever, reranker, query, embedding_model, top_k, reranker_top_k, metadata_filters = None):
  query_vector = create_query_embedding(query, embedding_model)
  query_filter = build_metadata_filter(metadata_filters)

  dense_results = search_points(qdrant_client,
                                COLLECTION_NAME,
                                query_vector,
                                limit = top_k,
                                filters = query_filter).points
  bm25_results = bm25_retriever.retrieve(query, limit = top_k, metadata_filters = metadata_filters)

  dense_chunks = {p.payload["text"]: _make_chunk(p.payload["text"],
                                                 {k: v for k, v in p.payload.items() if k != "text"},
                                                 p.score) for p in dense_results}

  bm25_chunks = {node.text: _make_chunk(node.text, node.metadata, score) for node, score in bm25_results}

  # combine the results
  merged = {**dense_chunks, **bm25_chunks}  # the union in dictionary
  all_chunks = list(merged.values())

  # reranking
  reranked_chunks = reranker.rerank(query, all_chunks, reranker_top_k)

  return {
      "dense_chunks": list(dense_chunks.values()),
      "bm25_chunks": list(bm25_chunks.values()),
      "all_chunks": list(all_chunks),
      "reranked_chunks": reranked_chunks
  }

Writing RAG_module/retrieval_pipeline.py

## `citation_verifier.py`
* 檢查 LLM 回答裡引用的標籤，是不是真的存在於 citation_map 裡
> * 這時 recall 高就很重要，因為低的 recall 表示 citation_map 本身就沒有抓到關鍵訊息，再怎麼精準引用也沒有用。

In [ ]:
%%writefile RAG_module/citation_verifier.py
import re

def extract_cited_tags(answer_text):
  return set(re.findall(r"\[S\d+\]", answer_text))


def verify_citations(answer_text, citation_map):
  # check whether the labels cited truly exist in the citation map
  cited_tags = extract_cited_tags(answer_text)
  valid_keys = {f"[{tag}]" for tag in citation_map.keys()}

  valid_tags = cited_tags & valid_keys
  invalid_tags = cited_tags - valid_keys

  return {
      "cited_tags": cited_tags,
      "valid_tags": valid_tags,
      "invalid_tags": invalid_tags,
      "has_hallucinated_citation": len(invalid_tags) > 0}

Writing RAG_module/citation_verifier.py

## `faithfulness_checker.py`
* 檢查被引用的內容是否語意上甚至邏輯上支持答案或結論

In [ ]:
%%writefile RAG_module/faithfulness_checker.py
import re
import time
from groq import Groq, RateLimitError
import RAG_module.api

_client = Groq()


def _judge_faithfulness(question, answer_text, combined_source_text, judge_model, max_retries = 5):
  prompt = f"""You are a fact-checking assistant.
  You are given the ORIGINAL QUESTION, a set of SOURCE TEXT excerpts
  (separated by "---", each prefixed with a tag like [S1]), and an ANSWER
  that was generated based on these source texts.

  Determine whether the source texts, taken TOGETHER, support the answer
  as a whole. The answer must be about the same specific subject/entity/case
  as stated in the source texts, not merely about the same general topic.
  It is fine if no single excerpt alone is sufficient, as long as they
  jointly support the answer.
  Reply with only "yes" or "no".

  Original question: {question}

  Source text(s): {combined_source_text}

  Answer: {answer_text}

  Do the source texts, taken together, support this answer?"""

  for attempt in range(max_retries):
    try:
      response = _client.chat.completions.create(
          model = judge_model,
          messages = [{"role": "user", "content": prompt}]
      )
      return response.choices[0].message.content.strip().lower() == "yes"

    except RateLimitError as e:
      if attempt == max_retries - 1:
        raise
      wait_seconds = 2 ** (attempt + 1)
      print(f"{attempt + 1}/{max_retries}: [Faithfulness Checker] encounters rate limit, wait for {wait_seconds} seconds to retry...")
      time.sleep(wait_seconds)


def check_faithfulness(question, answer_text, citation_map, judge_model):
  if not citation_map:
    return {"supported": False, "reason": "no context retrieved to check against"}

  combined_source_text = "\n---\n".join(
      f"[{tag}] {info['text']}" for tag, info in citation_map.items()
  )

  supported = _judge_faithfulness(question, answer_text, combined_source_text, judge_model)

  return {"supported": supported}

Writing RAG_module/faithfulness_checker.py

## `main.py`

In [ ]:
%%writefile RAG_module/main.py
from RAG_module.config import COLLECTION_NAME, EMBEDDING_DIM, DOCUMENT_DIR
from RAG_module.config import CHUNK_SIZE, CHUNK_OVERLAP, TOP_K, RERANKER_TOP_K, LLM_MODEL, EMBEDDING_MODEL, RERANKER_MODEL, JUDGE_MODEL
from RAG_module.loader import load_documents
from RAG_module.metadata_loader import load_document_metadata, CATEGORIES, DOC_TYPES
from RAG_module.kb_manager import is_kb_outdated, save_checksum
from RAG_module.chunker import create_nodes
from RAG_module.embedding_service import create_document_embedding, create_query_embedding
from RAG_module.vector_store import create_vector_store
from RAG_module.qdrant_repository import (
    create_collection,
    collection_exists,
    create_points,
    upsert_points
)
from RAG_module.retrieval_pipeline import run_retrieval
from RAG_module.bm25_retriever import BM25Retriever
from RAG_module.reranker import Reranker
from RAG_module.prompt_builder import build_prompt
from RAG_module.gemini_client import setup_gemini, ask_gemini
from RAG_module.citation_verifier import verify_citations
from RAG_module.faithfulness_checker import check_faithfulness


def main():
  # 0: initializations
  reranker = Reranker(RERANKER_MODEL)
  gemini_client = setup_gemini()
  qdrant_client = create_vector_store()

  # 1: load the documents
  documents = load_documents()

  # 2: chunking the Documents into TextNodes with metadata extraction
  nodes = create_nodes(documents, CHUNK_SIZE, CHUNK_OVERLAP)
  metadata_lookup = load_document_metadata()
  for node in nodes:
    file_name = node.metadata.get("file_name")
    extracted = metadata_lookup.get(file_name, {})
    node.metadata.update(extracted)

  bm25_retriever = BM25Retriever(nodes)

  outdated, current_checksum = is_kb_outdated(DOCUMENT_DIR, EMBEDDING_MODEL)
  if outdated or not collection_exists(qdrant_client, COLLECTION_NAME):
    ## start building the knowledge base ##
    print("building knowledge base...")

    # 3: transform TextNodes into Points to be stored in Qdrant
    points = create_points(nodes, create_document_embedding, EMBEDDING_MODEL)

    # 4: create collection
    create_collection(qdrant_client,
                      COLLECTION_NAME,
                      EMBEDDING_DIM)

    # 5: upsert the points into the collection created
    upsert_points(qdrant_client,
                  COLLECTION_NAME,
                  points)

    # save the current checksum
    save_checksum(current_checksum)

    print("knowledge base created.")
    ## end building the knowledge base ##

  else:
    print("Using existing knowledge base.")

  print("設定檢索篩選條件（每一項都可以直接按 Enter 跳過，不套用該項）")
  print()

  metadata_filters = {}

  print("主題分類：")
  for cat in CATEGORIES:
    print(f"- {cat}")

  category_input = input("輸入主題分類關鍵字（例如「氣候」）：").strip()
  if category_input:
    matches = [c for c in CATEGORIES if category_input in c]
    if len(matches) == 1:
      metadata_filters["category"] = matches[0]
      print(f"  已套用：category = {matches[0]}")
    elif len(matches) > 1:
      print(f"  關鍵字對應到多個分類：{matches}，這項不套用篩選")
    else:
      print(f"  找不到符合的分類，這項不套用篩選")

  print()
  print("文件性質：")
  for dt in DOC_TYPES:
    print(f"- {dt}")

  doctype_input = input("輸入文件性質關鍵字（例如「政策報告」）：").strip()
  if doctype_input:
    matches = [dt for dt in DOC_TYPES if doctype_input in dt]
    if len(matches) == 1:
      metadata_filters["doc_type"] = matches[0]
      print(f"  已套用：doc_type = {matches[0]}")
    elif len(matches) > 1:
      print(f"  關鍵字對應到多個文件性質：{matches}，這項不套用篩選")
    else:
      print(f"  找不到符合的文件性質，這項不套用篩選")

  if not metadata_filters:
    metadata_filters = None
  print()

  try:

    while True:
      query = input("\nQuestion: ")

      if query.lower() == "exit":
        break

      # 6: the retrieval step
      retrieval_result = run_retrieval(qdrant_client,
                                       bm25_retriever,
                                       reranker,
                                       query,
                                       EMBEDDING_MODEL,
                                       TOP_K,
                                       RERANKER_TOP_K,
                                       metadata_filters = metadata_filters)
      reranked_chunks = retrieval_result["reranked_chunks"]

      # 7: construct the augmented prompt
      prompt, citation_map = build_prompt(query,
                                          reranked_chunks)

      # 8: obtain the LLM's response with the augmented query as input
      answer = ask_gemini(gemini_client,
                          prompt,
                          LLM_MODEL)

      print()
      print(answer)
      print()

      # check if citations are valid, meaning that they exist in the citation map
      print("本次可引用的來源：")
      for tag, info in citation_map.items():
        loc = info["file_name"] or "未知來源"
        if info["page_label"]:
          loc += f" 第{info['page_label']}頁"
        print(f"  {tag}: {loc}")
      print()

      verification = verify_citations(answer, citation_map)
      if verification["has_hallucinated_citation"]:
        print(f"⚠️ 偵測到幻覺引用：{verification['invalid_tags']}（這些標籤不存在於本次 context 中）")
      else:
        print("✅ 引用標籤檢查通過")
      print()

      # check if valid citations truly support the LLM's answer
      faithfulness = check_faithfulness(query, answer, citation_map, JUDGE_MODEL)
      if faithfulness["supported"]:
        print("✅ 引用內容語意查核通過")
      else:
        print("⚠️ 這一輪檢索到的來源，合起來似乎無法支持這個回答")
      print()

  finally:

    # close the client
    qdrant_client.close()

if __name__ == "__main__":
  main()

Writing RAG_module/main.py

In [ ]:
## 執行 main
from RAG_module.main import main

try:
  qdrant_client.close()

except:
  pass

main()

/usr/local/lib/python3.12/dist-packages/jieba/_compat.py:18: UserWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html. The pkg_resources package is slated for removal as early as 2025-11-30. Refrain from using this package or pin to Setuptools<81.
  import pkg_resources
Building prefix dict from the default dictionary ...
DEBUG:jieba:Building prefix dict from the default dictionary ...
Loading model from cache /tmp/jieba.cache
DEBUG:jieba:Loading model from cache /tmp/jieba.cache
Loading model cost 0.807 seconds.
DEBUG:jieba:Loading model cost 0.807 seconds.
Prefix dict has been built successfully.
DEBUG:jieba:Prefix dict has been built successfully.

Loading weights:   0%|          | 0/393 [00:00<?, ?it/s]

Using existing knowledge base.
設定檢索篩選條件（每一項都可以直接按 Enter 跳過，不套用該項）

主題分類：
- 支付清算
- 貨幣政策
- 氣候金融
- 央行比較法制
- 其他
輸入主題分類關鍵字（例如「氣候」）：什麼是貨幣政策？
  找不到符合的分類，這項不套用篩選

文件性質：
- 本行政策報告
- 國際準則中譯本
- 比較法選輯
- 制度說明手冊
- 其他
輸入文件性質關鍵字（例如「政策報告」）：


Question: 什麼是貨幣政策？
載入本地 embedding 模型：BAAI/bge-m3（第一次執行需要下載模型檔案，請稍候）

Loading weights:   0%|          | 0/391 [00:00<?, ?it/s]

貨幣政策旨在維持本國貨幣體系之健全及穩定，以確保國家經濟之穩定與所需信心。它包括使用貨幣市場操作以影響整體金融與經濟活動，故一國支付系統對貨幣政策之有效執行至為重要。

因此，貨幣政策的目的是維持物價穩定，並支持政府之整體經濟政策，若無損於此一首要目標。

(貨幣政策旨在維持本國貨幣體系之健全及穩定，以確保國家經濟之穩定與所需信心) [S1]
(為維持物價穩定，決定貨幣政策之原則及策略；) [S4]
(故一國支付系統對貨幣政策之有效執行至為重要。) [S3]
(只要無損於此一首要目標，貨幣政策應支持政府之整體經濟政策。) [S5]

本次可引用的來源：
  S1: 各國中央銀行法選輯-2025年版-下冊.pdf 第52頁
  S2: 各國中央銀行法選輯-2025年版-下冊.pdf 第52頁
  S3: 一國支付系統發展之一般準則.pdf 第7頁
  S4: 各國中央銀行法選輯-2025年版-上冊.pdf 第57頁
  S5: 各國中央銀行法選輯-2025年版-上冊.pdf 第14頁

✅ 引用標籤檢查通過

✅ 引用內容語意查核通過


Question: exit

# 以下進入模型表現評估

## `eval_dataset.json`
* 建立評估資料

In [ ]:
## create Evaluation Dataset
import json

dataset = [
    {"question": "Did An-Tsu take ECON 516?", "answer": "yes", "source": "ECON 516"},
    {"question": "Did An-Tsu take ECON 400?", "answer": "I don't know", "source": None},
    {"question": "Did An-Tsu take ECON 585?", "answer": "yes", "source": "ECON 585"},
    {"question": "Did An-Tsu take STAT 535?", "answer": "yes", "source": "STAT 535"},
    {"question": "Did An-Tsu take STAT 600?", "answer": "I don't know", "source": None},
    {"question": "Did An-Tsu take CSE 142?", "answer": "yes", "source": "CSE 142"},
    {"question": "What score did An-Tsu get on ECON 501?", "answer": "4.0", "source": "ECON 501"},
    {"question": "What score did An-Tsu get on ECON 499?", "answer": "I don't know", "source": None},
    {"question": "Did An-Tsu have a degree in statistics?", "answer": "yes", "source": "MASTER OF SCIENCE (STATISTICS)"},
    {"question": "What is An-Tsu highest degree?", "answer": "doctor", "source": "DOCTOR OF PHILOSOPHY (ECONOMICS)"}
]

with open("RAG_module/eval_dataset.json", "w") as f:
  json.dump(dataset, f, indent = 2)

print("eval_dataset.json created.")

eval_dataset.json created.

In [ ]:
## create evaluation dataset
import json

dataset = [
  {
    "question": "依據「因應氣候變遷策略方案」，中央銀行因應氣候變遷的政策目標有哪兩項？",
    "answer": "強化經濟金融體系因應氣候變遷風險之韌性；協助經濟體系順利轉型至永續之綠色經濟",
    "source": "強化經濟金融體系因應氣候變遷風險之韌性",
    "source_file": "因應氣候變遷策略方案.pdf",
    "expected_filters": {"category": "氣候金融"}
  },
  {
    "question": "NGFS（綠色金融體系網絡）是在哪一年、於哪個城市成立的？",
    "answer": "2017年12月，在巴黎（第一次「一個星球峰會」中）成立",
    "source": "2017 年 12 月在巴黎舉行之第一次",
    "source_file": "因應氣候變遷策略方案.pdf",
    "expected_filters": {"category": "氣候金融"}
  },
  {
    "question": "依據瑞士再保險公司資料，近10年(2012-2021年)全球極端氣候災害造成的經濟損失是多少？跟1980年代相比呢？",
    "answer": "近10年(2012-2021年)約1.93兆美元，遠高於1980年代的2,140億美元",
    "source": "1.93 兆美元",
    "source_file": "因應氣候變遷策略方案.pdf",
    "expected_filters": {"category": "氣候金融"}
  },
  {
    "question": "「綠天鵝」(green swan)這個詞指的是什麼？",
    "answer": "指氣候相關風險引發之系統性金融危機，具有災難性及不可逆性",
    "source": "綠天鵝係指氣候相關風險引發之系統性金融危機",
    "source_file": "因應氣候變遷策略方案.pdf",
    "expected_filters": None
  },
  {
    "question": "依據「貨幣政策工具」，銀行向央行申請短期融通，期限最長不能超過幾天？",
    "answer": "十天",
    "source": "期限不能超過十天",
    "source_file": "貨幣政策工具.pdf",
    "expected_filters": {"category": "貨幣政策"}
  },
  {
    "question": "我國中央銀行儲蓄券最後是什麼時候全部到期兌償完畢的？此後有沒有再發行？",
    "answer": "民國81年1月全部到期兌償完畢，此後未再發行",
    "source": "81年1月全部到期兌償完畢",
    "source_file": "貨幣政策工具.pdf",
    "expected_filters": {"category": "貨幣政策"}
  },
  {
    "question": "央行重貼現的合格票據中，工商業票據跟農業票據的重貼現期限最長分別是幾天？",
    "answer": "工商業票據最長不得超過九十天，農業票據最長不得超過一百八十天",
    "source": "農業票據最長不得超過一百八十天",
    "source_file": "貨幣政策工具.pdf",
    "expected_filters": {"category": "貨幣政策"}
  },
  {
    "question": "依據「中華民國支付及清算系統」，截至民國111年底，我國信用卡流通卡數約幾張？",
    "answer": "約5,624萬張",
    "source": "流通卡數約5,624萬張",
    "source_file": "中華民國支付及清算系統.pdf",
    "expected_filters": {"category": "支付清算"}
  },
  {
    "question": "在支付清算領域中，「集中交易對手」（central counterparty, CCP）的定義是什麼？",
    "answer": "擔任某些特定契約（例如在特定交易所執行之契約）所有賣方之買方及所有買方之賣方的機構",
    "source": "所有賣方之買方及所有買方之賣方的機構",
    "source_file": "支付與清算系統間之相互依存關係.pdf",
    "expected_filters": {"category": "支付清算"}
  },
  {
    "question": "依據這批文件，台灣2026年的信用卡循環利率上限是多少？",
    "answer": "I don't know",
    "source": None,
    "source_file": None,
    "expected_filters": None
  },

  # ===== 新增 30 題 =====
  # 支付清算（新增10題）
  {
    "question": "截至民國111年底，同資系統參加單位共幾家？包括哪些類型的機構？",
    "answer": "共86家，包括71家銀行、8家票券金融公司、中華郵政公司，以及財金公司、票交所、證交所、櫃買中心、集保結算所及聯卡中心等6家結算機構",
    "source": "同資系統參加單位共86家",
    "source_file": "中華民國支付及清算系統.pdf",
    "expected_filters": {"category": "支付清算"}
  },
  {
    "question": "「QR Code共通支付標準」是哪一年由財金公司協同金融機構制定的？",
    "answer": "民國106年",
    "source": "財金公司協同金融機構於民國106年制定",
    "source_file": "中華民國支付及清算系統.pdf",
    "expected_filters": {"category": "支付清算"}
  },
  {
    "question": "信用卡結算系統由哪個機構營運？自哪一年幾月起連結同資系統辦理清算？",
    "answer": "由聯卡中心（聯合信用卡處理中心）營運，自民國102年11月起連結同資系統辦理清算",
    "source": "信用卡結算系統由聯卡中心營運",
    "source_file": "中華民國支付及清算系統.pdf",
    "expected_filters": {"category": "支付清算"}
  },
  {
    "question": "民國111年信用卡結算系統處理的交易金額跟簽帳筆數約多少？",
    "answer": "交易金額約1.6兆元，筆數約13.1億筆",
    "source": "處理交易金額約1.6兆元",
    "source_file": "中華民國支付及清算系統.pdf",
    "expected_filters": {"category": "支付清算"}
  },
  {
    "question": "依據「一國支付系統發展之一般準則」，一般準則共有幾項？分成哪四大面向？",
    "answer": "共14項，分成銀行體系、計畫、制度性架構、基礎設施四大面向",
    "source": "一般準則總計 14 項",
    "source_file": "一國支付系統發展之一般準則.pdf",
    "expected_filters": {"category": "支付清算"}
  },
  {
    "question": "「一國支付系統發展之一般準則」裡的準則1，名稱是什麼？",
    "answer": "維持中央銀行居於核心地位",
    "source": "準則 1. 維持中央銀行居於核心地位",
    "source_file": "一國支付系統發展之一般準則.pdf",
    "expected_filters": {"category": "支付清算"}
  },
  {
    "question": "「一國支付系統發展之一般準則」裡的準則10，名稱是什麼？",
    "answer": "加強法律之確定性",
    "source": "準則 10. 加強法律之確定性",
    "source_file": "一國支付系統發展之一般準則.pdf",
    "expected_filters": {"category": "支付清算"}
  },
  {
    "question": "「一國支付系統發展之一般準則」裡的準則5，名稱是什麼？",
    "answer": "制訂明確之優先順序",
    "source": "準則 5. 制訂明確之優先順序",
    "source_file": "一國支付系統發展之一般準則.pdf",
    "expected_filters": {"category": "支付清算"}
  },
  {
    "question": "CLS是什麼機制的縮寫？主要用什麼方式清算外匯交易？",
    "answer": "CLS是Continuous Linked Settlement（持續連結清算）的縮寫，透過CLS銀行的會計帳簿，以款對款同步收付（PVP）方式進行資金撥轉",
    "source": "持續連結清算(Continuous Linked Settlement, CLS)",
    "source_file": "支付與清算系統間之相互依存關係.pdf",
    "expected_filters": {"category": "支付清算"}
  },
  {
    "question": "依據「支付與清算系統間之相互依存關係」，CPSS提出因應相互依存關係的三項重大挑戰是什麼？",
    "answer": "(i)採取廣泛的風險管理視野；(ii)系統、機構或服務提供者具備之風險控管機制應能與其在全球基礎設施扮演之角色相稱；(iii)在相互依存利害關係人間進行廣泛協調",
    "source": "採取廣泛的風險管理視野",
    "source_file": "支付與清算系統間之相互依存關係.pdf",
    "expected_filters": {"category": "支付清算"}
  },
  {
    "question": "SWIFT的中文全稱是什麼？",
    "answer": "環球銀行金融電信協會",
    "source": "環球銀行金融電信協會",
    "source_file": "支付與清算系統間之相互依存關係.pdf",
    "expected_filters": {"category": "支付清算"}
  },

  # 貨幣政策（新增6題）
  {
    "question": "依據「貨幣政策工具」，中央銀行的貨幣政策工具主要依序包括哪五大類制度？",
    "answer": "準備金制度、貼現窗口制度、公開市場操作、金融機構轉存款、選擇性信用管理",
    "source": "依序說明我國準備金制度、貼現窗口制度、公開市場操作",
    "source_file": "貨幣政策工具.pdf",
    "expected_filters": {"category": "貨幣政策"}
  },
  {
    "question": "支票存款、活期存款、儲蓄存款、定期存款的準備率法定上限各為多少？",
    "answer": "支票存款25%、活期存款25%、儲蓄存款15%、定期存款15%（其他各種負債25%）",
    "source": "支票存款 25%、活期存款 25%、儲蓄存款 15%、定期存款 15%",
    "source_file": "貨幣政策工具.pdf",
    "expected_filters": {"category": "貨幣政策"}
  },
  {
    "question": "中央銀行定期存單發行面額分為哪三種？",
    "answer": "500萬元、1,000萬元、與1億元三種",
    "source": "500萬元、1,000萬元、與1億元等三種",
    "source_file": "貨幣政策工具.pdf",
    "expected_filters": {"category": "貨幣政策"}
  },
  {
    "question": "銀行申請短期融通的金額，每月平均不得超過當月應提存款準備金的多少百分比？",
    "answer": "10%",
    "source": "每月平均不得超過當月應提存款準備金的10%",
    "source_file": "貨幣政策工具.pdf",
    "expected_filters": {"category": "貨幣政策"}
  },
  {
    "question": "銀行申請擔保放款之再融通，期限最長不能超過幾天？",
    "answer": "三百六十天",
    "source": "期限最長不能超過三百六十天",
    "source_file": "貨幣政策工具.pdf",
    "expected_filters": {"category": "貨幣政策"}
  },
  {
    "question": "民國87年7月後，依據哪個法規的實施，中央銀行不得再發行國庫券？",
    "answer": "「短期借款暨國庫券發行條例」",
    "source": "短期借款暨國庫券發行條例",
    "source_file": "貨幣政策工具.pdf",
    "expected_filters": {"category": "貨幣政策"}
  },

  # 氣候金融（新增5題）
  {
    "question": "依據「因應氣候變遷策略方案」，氣候變遷風險分為哪兩類？",
    "answer": "有形風險(physical risks)及轉型風險(transition risks)",
    "source": "有形風險(physical risks)及轉型風險(transition risks)",
    "source_file": "因應氣候變遷策略方案.pdf",
    "expected_filters": {"category": "氣候金融"}
  },
  {
    "question": "本行因應氣候變遷的三大核心策略是什麼？",
    "answer": "協助發展綠色永續投融資環境；積極建構本行對氣候議題之專業能力；本行營運與外匯存底管理運用納入氣候風險考量",
    "source": "協助發展綠色永續投融資環境",
    "source_file": "因應氣候變遷策略方案.pdf",
    "expected_filters": {"category": "氣候金融"}
  },
  {
    "question": "巴塞爾銀行監理委員會(BCBS)於2022年6月發布了幾項「氣候相關金融風險之有效管理及監理原則」？",
    "answer": "18項",
    "source": "發布 18 項「氣候相關金融風險之有效管理及監理原則」",
    "source_file": "因應氣候變遷策略方案.pdf",
    "expected_filters": {"category": "氣候金融"}
  },
  {
    "question": "依據本行2022年6月底的調查，40家本國銀行中有幾家已設立永續金融專責單位？",
    "answer": "29家",
    "source": "已有 29 家銀行或所屬金控公司在內部設立永續金融專責單位",
    "source_file": "因應氣候變遷策略方案.pdf",
    "expected_filters": {"category": "氣候金融"}
  },
  {
    "question": "截至2022年10月3日，NGFS有幾家央行及金融監理機構成為會員？",
    "answer": "121家",
    "source": "全球已有 121 家央行及金融監理機構成為 NGFS 成員",
    "source_file": "因應氣候變遷策略方案.pdf",
    "expected_filters": {"category": "氣候金融"}
  },

  # 央行比較法制（新增6題，含跨國混淆測試）
  {
    "question": "依據「西班牙銀行自治法」，總裁及副總裁的任期為幾年？期滿是否可連任同一職務？",
    "answer": "任期為6年，且不得續任同一職務",
    "source": "總裁及副總裁之任期為 6 年，且不得續任同一職務",
    "source_file": "各國中央銀行法選輯-2025年版-上冊.pdf",
    "expected_filters": {"category": "央行比較法制"}
  },
  {
    "question": "依據「南非準備銀行法」，總裁及副總裁的任期為幾年？",
    "answer": "任期均為5年；期滿經總統徵詢部長及理事會後，得續任命之，但任期不得逾5年",
    "source": "總裁及副總裁任期均為 5 年",
    "source_file": "各國中央銀行法選輯-2025年版-上冊.pdf",
    "expected_filters": {"category": "央行比較法制"}
  },
  {
    "question": "依據「以色列銀行法」，總裁的任期為幾年？期滿後可連任幾次？",
    "answer": "任期為5年，期滿得續派連任1次",
    "source": "總裁任期為 5 年，期滿得續派連任 1 次",
    "source_file": "各國中央銀行法選輯-2025年版-上冊.pdf",
    "expected_filters": {"category": "央行比較法制"}
  },
  {
    "question": "依據「印度尼西亞銀行法」，理事會成員的任期為幾年？",
    "answer": "5年",
    "source": "理事會成員任期 5 年",
    "source_file": "各國中央銀行法選輯-2025年版-下冊.pdf",
    "expected_filters": {"category": "央行比較法制"}
  },
  {
    "question": "依據「中華民國中央銀行法」第一條，本行經營之目標有哪四項？",
    "answer": "促進金融穩定；健全銀行業務；維護對內及對外幣值之穩定；於上列目標範圍內，協助經濟之發展",
    "source": "促進金融穩定",
    "source_file": "各國中央銀行法選輯-2025年版-上冊.pdf",
    "expected_filters": {"category": "央行比較法制"}
  },
  {
    "question": "「各國中央銀行法選輯（2025年版）」上冊跟下冊分別收錄了哪幾個國家的中央銀行法？",
    "answer": "上冊收錄西班牙、土耳其、南非、以色列；下冊收錄挪威、阿拉伯聯合大公國、印尼、巴哈馬",
    "source": "西班牙銀行自治法",
    "source_file": "各國中央銀行法選輯-2025年版-上冊.pdf",
    "expected_filters": {"category": "央行比較法制"}
  },

  # 負樣本（新增2題，故意問資料庫沒有的內容）
  {
    "question": "依據這批文件，2026年台灣中央銀行的重貼現率是多少？",
    "answer": "I don't know",
    "source": None,
    "source_file": None,
    "expected_filters": None
  },
  {
    "question": "依據這批文件，美國聯邦準備法（Federal Reserve Act）對總裁任期有何規定？",
    "answer": "I don't know",
    "source": None,
    "source_file": None,
    "expected_filters": None
  }
]

with open("RAG_module/eval_dataset.json", "w") as f:
  json.dump(dataset, f, indent = 2, ensure_ascii = False)

print(f"eval_dataset.json created with {len(dataset)} questions.")

eval_dataset.json created with 40 questions.

## `evaluator.py`
* 評估時會需要使用的各種計算
> * 包含 recall, answer quality

In [ ]:
%%writefile RAG_module/evaluator.py
import json
import re
import time
import unicodedata
import RAG_module.api
from google import genai
from groq import Groq, RateLimitError
from RAG_module.citation_verifier import verify_citations
from RAG_module.faithfulness_checker import check_faithfulness


def normalize(text):
  text = unicodedata.normalize('NFKC', text)
  return re.sub(r'\s+', '', text).lower()


def load_eval_dataset(path = "RAG_module/eval_dataset.json"):
  with open(path, "r") as f:
    return json.load(f)


def eval_retrieval(dataset, retrieve_fn, configs):
  results = []

  for item in dataset:
    if item["source"] is None:
      continue

    retrieved_texts = retrieve_fn(item["question"], configs, item.get("expected_filters"))
    hit = any(normalize(item["source"]) in normalize(text) for text in retrieved_texts)

    results.append({
        "question": item["question"],
        "source": item["source"],
        "hit": hit
    })

  recall = sum(r["hit"] for r in results) / len(results)

  return recall, results


#_client = genai.Client()
_client = Groq()

def judge_answer(question, expected, actual, judge_model, max_retries = 5):
  prompt = f"""You are an evaluation assistant.
  Judge whether the actual answer correctly answers the question.
  The correctness is based on the information provided in the expected answer.
  Note that the actual answer might provide some redundant information, which
  should not affect whether the actual answer is correct or not. Also, if both
  the expected answer and actual answer are like "I don't know", then the actual
  answer correctly answers the question. Reply with only "yes" or "no".

  Question: {question}
  Expected answer: {expected}
  Actual answer: {actual}

  Is the actual answer correct?"""

  for attempt in range(max_retries):
    try:
      response = _client.chat.completions.create(
          model = judge_model,
          messages = [{"role": "user", "content": prompt}]
      )
      return response.choices[0].message.content.strip().lower() == "yes"

    except RateLimitError as e:
      if attempt == max_retries - 1:
        raise
      wait_seconds = 2 ** (attempt + 1)
      print(f"{attempt + 1}/{max_retries}: [Judge] encounters rate limit, wait for {wait_seconds} seconds to retry...")
      time.sleep(wait_seconds)

  # with google gemini
  #response = _client.models.generate_content(
  #    model = JUDGE_MODEL,
  #    contents = prompt
  #)

  # return response.text.strip().lower() == "yes"

def eval_answer(dataset, rag_fn, configs):
  results = []

  for item in dataset:
    actual, citation_map = rag_fn(item["question"], configs, item.get("expected_filters"))

    correct = judge_answer(item["question"], item["answer"], actual, configs["judge_model"])
    citation_check = verify_citations(actual, citation_map)
    faithfulness_check = check_faithfulness(item["question"], actual, citation_map, configs["judge_model"])

    results.append({
        "question": item["question"],
        "expected": item["answer"],
        "actual": actual,
        "correct": correct,
        "has_hallucinated_citation": citation_check["has_hallucinated_citation"],
        "invalid_tags": citation_check["invalid_tags"],
        "faithfulness_supported": faithfulness_check["supported"],
    })

  n = len(results)
  scores = {
      "answer_quality": sum(r["correct"] for r in results) / n,
      "citation_validity": sum(not r["has_hallucinated_citation"] for r in results) / n,
      "faithfulness": sum(r["faithfulness_supported"] for r in results) / n,
  }

  return scores, results

Writing RAG_module/evaluator.py

## `experiment_tracker.py`
* 紀錄參數組合與對應評估指標數值

In [ ]:
%%writefile RAG_module/experiment_tracker.py
import json
import os
import pandas as pd
from datetime import datetime


TRACKER_PATH = "RAG_module/experiments.json"

def load_experiments():
  if not os.path.exists(TRACKER_PATH):
    return []
  with open(TRACKER_PATH, "r") as f:
    return json.load(f)

def save_experiment(params, metrics, notes=""):
  experiments = load_experiments()
  record = {
      "id": len(experiments) + 1,
      "timestamp": datetime.now().strftime("%Y-%m-%d %H:%M"),
      "params": params,
      "metrics": metrics,
      "notes": notes
  }
  experiments.append(record)
  with open(TRACKER_PATH, "w") as f:
    json.dump(experiments, f, indent=2)

  print(f"Experiment #{record['id']} saved.")

def print_experiments():
  experiments = load_experiments()
  for exp in experiments:
    print(f"\n#{exp['id']} | {exp['timestamp']}")
    print(f"  params : {exp['params']}")
    print(f"  metrics: {exp['metrics']}")
    if exp['notes']:
      print(f"  notes  : {exp['notes']}")

def show_experiments():
  experiments = load_experiments()
  if not experiments:
    print("no experiments yet")
    return

  rows = []
  for exp in experiments:
    row = {"id": exp["id"], "timestamp": exp["timestamp"]}
    row.update(exp["params"])
    row.update(exp["metrics"])
    row["notes"] = exp["notes"]
    rows.append(row)

  df = pd.DataFrame(rows)
  return df

Writing RAG_module/experiment_tracker.py

## `recall_debugger.py`
* 負責診斷與調參輔助，方便快速迭代以調高 recall

In [ ]:
%%writefile RAG_module/recall_debugger.py
from RAG_module.retrieval_pipeline import run_retrieval
from RAG_module.experiment_tracker import save_experiment
from RAG_module.chunker import create_nodes
from RAG_module.loader import load_documents
from RAG_module.bm25_retriever import BM25Retriever
from RAG_module.reranker import Reranker
from RAG_module.embedding_service import create_document_embedding
from RAG_module.qdrant_repository import create_points, create_collection, upsert_points
from RAG_module.evaluator import normalize
from RAG_module.metadata_loader import load_document_metadata
from RAG_module.config import COLLECTION_NAME, DOCUMENT_DIR


def recall_debug(qdrant_client,
                 dataset,
                 chunk_size,
                 chunk_overlap,
                 embedding_model,
                 embedding_dim,
                 reranker_model,
                 top_k,
                 reranker_top_k,
                 llm_model,
                 judge_model,
                 rebuild_kb = False,
                 notes = ""):

  # step 1: rebuild nodes with metadata
  from llama_index.core.node_parser import SentenceSplitter
  documents = load_documents()
  nodes = create_nodes(documents, chunk_size, chunk_overlap)

  metadata_lookup = load_document_metadata()
  for node in nodes:
    file_name = node.metadata.get("file_name")
    extracted = metadata_lookup.get(file_name, {})
    node.metadata.update(extracted)

  # step 2: rebuild BM25
  bm25_retriever = BM25Retriever(nodes)

  # step 3: rebuild KB if necessary
  if rebuild_kb:
    create_collection(qdrant_client, COLLECTION_NAME, embedding_dim)
    points = create_points(nodes, create_document_embedding, embedding_model)
    upsert_points(qdrant_client, COLLECTION_NAME, points)

  # step 4: perform the diagnosis for each question in the evaluation set
  reranker = Reranker(reranker_model)
  diagnosis_results = []

  for item in dataset:
    if item["source"] is None:
      continue

    source = item["source"]
    query = item["question"]
    metadata_filters = item.get("expected_filters")

    # layer 1: does the chunk exist?
    chunk_exists = any(normalize(source) in normalize(node.text) for node in nodes)

    # layer 2: are the keywords retrieved?
    result = run_retrieval(qdrant_client, bm25_retriever, reranker, query, embedding_model, top_k, reranker_top_k, metadata_filters = metadata_filters)
    dense_hit = any(normalize(source) in normalize(chunk["text"]) for chunk in result["dense_chunks"])
    bm25_hit = any(normalize(source) in normalize(chunk["text"]) for chunk in result["bm25_chunks"])

    # layer 3: are the keywords still captured after reranking?
    all_chunks = result["all_chunks"]
    rerank_hit = any(normalize(source) in normalize(chunk["text"]) for chunk in result["reranked_chunks"])

    diagnosis_results.append({
        "question": query,
        "source": source,
        "chunk_exists": chunk_exists,
        "dense_hit": dense_hit,
        "bm25_hit": bm25_hit,
        "rerank_hit": rerank_hit,
        "all_chunks": all_chunks
    })

  # step 5: print the diagnostic report
  print(f"\n{'='*60}")
  print(f"診斷參數：chunk_size = {chunk_size}, chunk_overlap = {chunk_overlap}, top_k = {top_k}, reranker_top_k = {reranker_top_k}")
  print(f"{'='*60}\n")

  recall_hits = 0
  for r in diagnosis_results:
    recall_hits += r["rerank_hit"]

    print(f"問題：{r['question']}")
    print(f"  source         : {r['source']}")
    print(f"  chunk exists   : {'✅' if r['chunk_exists'] else '❌'}")
    print(f"  dense hit      : {'✅' if r['dense_hit'] else '❌'}")
    print(f"  BM25 hit       : {'✅' if r['bm25_hit'] else '❌'}")
    print(f"  rerank hit     : {'✅' if r['rerank_hit'] else '❌'}")

    # diagnosis for implied actions
    if not r["chunk_exists"]:
      print(f"problem source: Chunking, adjust chunk_size or chunk_overlap")

    elif not r["dense_hit"] and not r["bm25_hit"]:
      print(f"problem source: Retrieval fails，consider to increase top_k or change embedding model")

    elif not r["dense_hit"]:
      print(f"problem source: keywords not in dense search but in BM25, consider to increase top_k")

    elif not r["bm25_hit"]:
      print(f"problem source: keywords not in BM25 but in dense search, consider to improve tokenization or increase top_k")

    elif not r["rerank_hit"]:
      dropped_by_reranker = [chunk for chunk in r["all_chunks"] if normalize(source) in normalize(chunk["text"])]
      print(f"problem source: Reranking, manually examine the contents for problematic chunks")
      for chunk in dropped_by_reranker:
        print(f"     ---")
        print(f"     ({chunk.get('file_name')} {chunk.get('page_label') or ''})")
        print(f"     {chunk["text"][:200]}")

      print(f"possible directions: adjust chunk_size/chunk_overlap, increase reranker_top_k, or change reranker model")

    else:
      print(f"✅ All pass")
    print()

  recall = recall_hits / len(diagnosis_results)
  print(f"{'=' * 60}")
  print(f"Recall@{reranker_top_k}: {recall:.3f}")
  print(f"{'=' * 60}\n")

  save_experiment(
      params = {"chunk_size": chunk_size,
                "chunk_overlap": chunk_overlap,
                "top_k": top_k,
                "reranker_top_k": reranker_top_k,
                "embedding_model": embedding_model,
                "reranker_model": reranker_model,
                "llm_model": llm_model,
                "judge_model": judge_model},
      metrics = {"recall": round(recall, 3)},
      notes = notes
  )

Writing RAG_module/recall_debugger.py

In [ ]:
## run the recall debugger
# llm_model and judge_model do not matter
from RAG_module.recall_debugger import recall_debug
from RAG_module.vector_store import create_vector_store
from RAG_module.evaluator import load_eval_dataset

recall_configs = {
    'chunk_size': 550,
    'chunk_overlap': 150,
    'embedding_model': "BAAI/bge-m3",
    'embedding_dim': 1024,
    'top_k': 12,
    'reranker_model': "BAAI/bge-reranker-v2-m3",
    'reranker_top_k': 8,
    'llm_model': "llama-3.1-8b-instant",
    'judge_model': "openai/gpt-oss-120b"
}

try:
  qdrant_client.close()

except:
  pass

qdrant_client = create_vector_store()
dataset = load_eval_dataset()

recall_debug(
    qdrant_client = qdrant_client,
    dataset = dataset,
    chunk_size = recall_configs['chunk_size'],
    chunk_overlap = recall_configs['chunk_overlap'],
    embedding_model = recall_configs['embedding_model'],
    embedding_dim = recall_configs['embedding_dim'],
    reranker_model = recall_configs['reranker_model'],
    top_k = recall_configs['top_k'],
    reranker_top_k = recall_configs['reranker_top_k'],
    llm_model = recall_configs['llm_model'],
    judge_model = recall_configs['judge_model'],
    rebuild_kb = True
)

[ocr_correction] 貨幣政策工具.pdf（page_label = 12）：「店 、1,000」→「500萬元、1,000」
[ocr_correction] 貨幣政策工具.pdf（page_label = 13）：「國庫六 發 行條例」→「國庫券發行條例」
some known errors are corrected for the documents.
載入本地 embedding 模型：BAAI/bge-m3（第一次執行需要下載模型檔案，請稍候）

Loading weights:   0%|          | 0/391 [00:00<?, ?it/s]

Loading weights:   0%|          | 0/393 [00:01<?, ?it/s]

============================================================
診斷參數：chunk_size = 550, chunk_overlap = 150, top_k = 12, reranker_top_k = 8
============================================================

問題：依據「因應氣候變遷策略方案」，中央銀行因應氣候變遷的政策目標有哪兩項？
  source         : 強化經濟金融體系因應氣候變遷風險之韌性
  chunk exists   : ✅
  dense hit      : ✅
  BM25 hit       : ✅
  rerank hit     : ✅
✅ All pass

問題：NGFS（綠色金融體系網絡）是在哪一年、於哪個城市成立的？
  source         : 2017 年 12 月在巴黎舉行之第一次
  chunk exists   : ✅
  dense hit      : ✅
  BM25 hit       : ✅
  rerank hit     : ✅
✅ All pass

問題：依據瑞士再保險公司資料，近10年(2012-2021年)全球極端氣候災害造成的經濟損失是多少？跟1980年代相比呢？
  source         : 1.93 兆美元
  chunk exists   : ✅
  dense hit      : ✅
  BM25 hit       : ✅
  rerank hit     : ✅
✅ All pass

問題：「綠天鵝」(green swan)這個詞指的是什麼？
  source         : 綠天鵝係指氣候相關風險引發之系統性金融危機
  chunk exists   : ✅
  dense hit      : ✅
  BM25 hit       : ❌
  rerank hit     : ✅
problem source: keywords not in BM25 but in dense search, consider to improve tokenization or increase top_k

問題：依據「貨幣政策工具」，銀行向央行申請短期融通，期限最長不能超過幾天？
  source         : 期限不能超過十天
  chunk exists   : ❌
  dense hit      : ❌
  BM25 hit       : ❌
  rerank hit     : ❌
problem source: Chunking, adjust chunk_size or chunk_overlap

問題：我國中央銀行儲蓄券最後是什麼時候全部到期兌償完畢的？此後有沒有再發行？
  source         : 81年1月全部到期兌償完畢
  chunk exists   : ✅
  dense hit      : ✅
  BM25 hit       : ✅
  rerank hit     : ✅
✅ All pass

問題：央行重貼現的合格票據中，工商業票據跟農業票據的重貼現期限最長分別是幾天？
  source         : 農業票據最長不得超過一百八十天
  chunk exists   : ✅
  dense hit      : ✅
  BM25 hit       : ✅
  rerank hit     : ✅
✅ All pass

問題：依據「中華民國支付及清算系統」，截至民國111年底，我國信用卡流通卡數約幾張？
  source         : 流通卡數約5,624萬張
  chunk exists   : ✅
  dense hit      : ✅
  BM25 hit       : ✅
  rerank hit     : ✅
✅ All pass

問題：在支付清算領域中，「集中交易對手」（central counterparty, CCP）的定義是什麼？
  source         : 所有賣方之買方及所有買方之賣方的機構
  chunk exists   : ✅
  dense hit      : ✅
  BM25 hit       : ✅
  rerank hit     : ✅
✅ All pass

問題：截至民國111年底，同資系統參加單位共幾家？包括哪些類型的機構？
  source         : 同資系統參加單位共86家
  chunk exists   : ✅
  dense hit      : ✅
  BM25 hit       : ✅
  rerank hit     : ✅
✅ All pass

問題：「QR Code共通支付標準」是哪一年由財金公司協同金融機構制定的？
  source         : 財金公司協同金融機構於民國106年制定
  chunk exists   : ✅
  dense hit      : ✅
  BM25 hit       : ✅
  rerank hit     : ✅
✅ All pass

問題：信用卡結算系統由哪個機構營運？自哪一年幾月起連結同資系統辦理清算？
  source         : 信用卡結算系統由聯卡中心營運
  chunk exists   : ✅
  dense hit      : ✅
  BM25 hit       : ✅
  rerank hit     : ✅
✅ All pass

問題：民國111年信用卡結算系統處理的交易金額跟簽帳筆數約多少？
  source         : 處理交易金額約1.6兆元
  chunk exists   : ✅
  dense hit      : ✅
  BM25 hit       : ✅
  rerank hit     : ✅
✅ All pass

問題：依據「一國支付系統發展之一般準則」，一般準則共有幾項？分成哪四大面向？
  source         : 一般準則總計 14 項
  chunk exists   : ✅
  dense hit      : ✅
  BM25 hit       : ✅
  rerank hit     : ✅
✅ All pass

問題：「一國支付系統發展之一般準則」裡的準則1，名稱是什麼？
  source         : 準則 1. 維持中央銀行居於核心地位
  chunk exists   : ✅
  dense hit      : ✅
  BM25 hit       : ✅
  rerank hit     : ✅
✅ All pass

問題：「一國支付系統發展之一般準則」裡的準則10，名稱是什麼？
  source         : 準則 10. 加強法律之確定性
  chunk exists   : ✅
  dense hit      : ✅
  BM25 hit       : ❌
  rerank hit     : ✅
problem source: keywords not in BM25 but in dense search, consider to improve tokenization or increase top_k

問題：「一國支付系統發展之一般準則」裡的準則5，名稱是什麼？
  source         : 準則 5. 制訂明確之優先順序
  chunk exists   : ✅
  dense hit      : ✅
  BM25 hit       : ✅
  rerank hit     : ✅
✅ All pass

問題：CLS是什麼機制的縮寫？主要用什麼方式清算外匯交易？
  source         : 持續連結清算(Continuous Linked Settlement, CLS)
  chunk exists   : ✅
  dense hit      : ✅
  BM25 hit       : ❌
  rerank hit     : ✅
problem source: keywords not in BM25 but in dense search, consider to improve tokenization or increase top_k

問題：依據「支付與清算系統間之相互依存關係」，CPSS提出因應相互依存關係的三項重大挑戰是什麼？
  source         : 採取廣泛的風險管理視野
  chunk exists   : ✅
  dense hit      : ✅
  BM25 hit       : ✅
  rerank hit     : ✅
✅ All pass

問題：SWIFT的中文全稱是什麼？
  source         : 環球銀行金融電信協會
  chunk exists   : ✅
  dense hit      : ❌
  BM25 hit       : ✅
  rerank hit     : ✅
problem source: keywords not in dense search but in BM25, consider to increase top_k

問題：依據「貨幣政策工具」，中央銀行的貨幣政策工具主要依序包括哪五大類制度？
  source         : 依序說明我國準備金制度、貼現窗口制度、公開市場操作
  chunk exists   : ✅
  dense hit      : ✅
  BM25 hit       : ✅
  rerank hit     : ✅
✅ All pass

問題：支票存款、活期存款、儲蓄存款、定期存款的準備率法定上限各為多少？
  source         : 支票存款 25%、活期存款 25%、儲蓄存款 15%、定期存款 15%
  chunk exists   : ✅
  dense hit      : ✅
  BM25 hit       : ✅
  rerank hit     : ✅
✅ All pass

問題：中央銀行定期存單發行面額分為哪三種？
  source         : 500萬元、1,000萬元、與1億元等三種
  chunk exists   : ✅
  dense hit      : ✅
  BM25 hit       : ✅
  rerank hit     : ✅
✅ All pass

問題：銀行申請短期融通的金額，每月平均不得超過當月應提存款準備金的多少百分比？
  source         : 每月平均不得超過當月應提存款準備金的10%
  chunk exists   : ✅
  dense hit      : ✅
  BM25 hit       : ✅
  rerank hit     : ✅
✅ All pass

問題：銀行申請擔保放款之再融通，期限最長不能超過幾天？
  source         : 期限最長不能超過三百六十天
  chunk exists   : ✅
  dense hit      : ✅
  BM25 hit       : ✅
  rerank hit     : ✅
✅ All pass

問題：民國87年7月後，依據哪個法規的實施，中央銀行不得再發行國庫券？
  source         : 短期借款暨國庫券發行條例
  chunk exists   : ✅
  dense hit      : ✅
  BM25 hit       : ✅
  rerank hit     : ✅
✅ All pass

問題：依據「因應氣候變遷策略方案」，氣候變遷風險分為哪兩類？
  source         : 有形風險(physical risks)及轉型風險(transition risks)
  chunk exists   : ✅
  dense hit      : ✅
  BM25 hit       : ❌
  rerank hit     : ✅
problem source: keywords not in BM25 but in dense search, consider to improve tokenization or increase top_k

問題：本行因應氣候變遷的三大核心策略是什麼？
  source         : 協助發展綠色永續投融資環境
  chunk exists   : ✅
  dense hit      : ✅
  BM25 hit       : ✅
  rerank hit     : ✅
✅ All pass

問題：巴塞爾銀行監理委員會(BCBS)於2022年6月發布了幾項「氣候相關金融風險之有效管理及監理原則」？
  source         : 發布 18 項「氣候相關金融風險之有效管理及監理原則」
  chunk exists   : ✅
  dense hit      : ✅
  BM25 hit       : ✅
  rerank hit     : ✅
✅ All pass

問題：依據本行2022年6月底的調查，40家本國銀行中有幾家已設立永續金融專責單位？
  source         : 已有 29 家銀行或所屬金控公司在內部設立永續金融專責單位
  chunk exists   : ✅
  dense hit      : ✅
  BM25 hit       : ✅
  rerank hit     : ✅
✅ All pass

問題：截至2022年10月3日，NGFS有幾家央行及金融監理機構成為會員？
  source         : 全球已有 121 家央行及金融監理機構成為 NGFS 成員
  chunk exists   : ✅
  dense hit      : ✅
  BM25 hit       : ✅
  rerank hit     : ✅
✅ All pass

問題：依據「西班牙銀行自治法」，總裁及副總裁的任期為幾年？期滿是否可連任同一職務？
  source         : 總裁及副總裁之任期為 6 年，且不得續任同一職務
  chunk exists   : ✅
  dense hit      : ✅
  BM25 hit       : ✅
  rerank hit     : ✅
✅ All pass

問題：依據「南非準備銀行法」，總裁及副總裁的任期為幾年？
  source         : 總裁及副總裁任期均為 5 年
  chunk exists   : ✅
  dense hit      : ✅
  BM25 hit       : ✅
  rerank hit     : ✅
✅ All pass

問題：依據「以色列銀行法」，總裁的任期為幾年？期滿後可連任幾次？
  source         : 總裁任期為 5 年，期滿得續派連任 1 次
  chunk exists   : ✅
  dense hit      : ✅
  BM25 hit       : ✅
  rerank hit     : ✅
✅ All pass

問題：依據「印度尼西亞銀行法」，理事會成員的任期為幾年？
  source         : 理事會成員任期 5 年
  chunk exists   : ✅
  dense hit      : ✅
  BM25 hit       : ✅
  rerank hit     : ✅
✅ All pass

問題：依據「中華民國中央銀行法」第一條，本行經營之目標有哪四項？
  source         : 促進金融穩定
  chunk exists   : ✅
  dense hit      : ✅
  BM25 hit       : ✅
  rerank hit     : ✅
✅ All pass

問題：「各國中央銀行法選輯（2025年版）」上冊跟下冊分別收錄了哪幾個國家的中央銀行法？
  source         : 西班牙銀行自治法
  chunk exists   : ✅
  dense hit      : ✅
  BM25 hit       : ✅
  rerank hit     : ✅
✅ All pass

============================================================
Recall@8: 0.97
============================================================

Experiment #1 saved.

In [ ]:
## print the experiments of recall debugging
from RAG_module.experiment_tracker import show_experiments
show_experiments()

,id,timestamp,chunk_size,chunk_overlap,top_k,reranker_top_k,embedding_model,reranker_model,llm_model,judge_model,recall,notes
0,1,2026-07-22 04:02,550,150,12,8,BAAI/bge-m3,BAAI/bge-reranker-v2-m3,llama-3.1-8b-instant,qwen/qwen3.6-27b,0.97,

## `answer_quality_debugger.py`
* 負責診斷與調參輔助，方便快速迭代以調高 answer quality
* 這邊雖然會計算其他指標，但是調參主角是 answer quality

In [ ]:
%%writefile RAG_module/answer_quality_debugger.py
from RAG_module.retrieval_pipeline import run_retrieval
from RAG_module.evaluator import normalize, judge_answer
from RAG_module.reranker import Reranker
from RAG_module.prompt_builder import build_prompt
from RAG_module.gemini_client import ask_gemini
from RAG_module.experiment_tracker import save_experiment
from RAG_module.loader import load_documents
from RAG_module.chunker import create_nodes
from RAG_module.metadata_loader import load_document_metadata
from RAG_module.bm25_retriever import BM25Retriever
from RAG_module.citation_verifier import verify_citations
from RAG_module.faithfulness_checker import check_faithfulness

def answer_quality_debug(qdrant_client,
                         gemini_client,
                         dataset,
                         chunk_size,
                         chunk_overlap,
                         embedding_model,
                         embedding_dim,
                         reranker_model,
                         top_k,
                         reranker_top_k,
                         llm_model,
                         judge_model,
                         notes = ""):

  # step 1: initialize reranker
  from llama_index.core.node_parser import SentenceSplitter
  documents = load_documents()
  nodes = create_nodes(documents, chunk_size, chunk_overlap)

  metadata_lookup = load_document_metadata()
  for node in nodes:
    file_name = node.metadata.get("file_name")
    extracted = metadata_lookup.get(file_name, {})
    node.metadata.update(extracted)

  bm25_retriever = BM25Retriever(nodes)
  reranker = Reranker(reranker_model)

  # step 2: perform the diagnosis for each question in the evaluation set
  diagnosis_results = []

  for item in dataset:
    query = item["question"]
    expected = item["answer"]
    source = item["source"]
    metadata_filters = item.get("expected_filters")

    # run retrieval
    result = run_retrieval(qdrant_client, bm25_retriever, reranker, query, embedding_model, top_k, reranker_top_k, metadata_filters = metadata_filters)

    # recall 有沒有 hit（跟 recall_debugger 邏輯一致）
    if source is None:
      recall_hit = None  # 這題不適用 recall 判斷

    else:
      recall_hit = any(normalize(source) in normalize(chunk["text"]) for chunk in result["all_chunks"])

    # rerank
    reranked_chunks = result["reranked_chunks"]

    # LLM 回答
    prompt, citation_map = build_prompt(query, reranked_chunks)
    actual = ask_gemini(gemini_client, prompt, llm_model)

    # judge
    correct = judge_answer(query, expected, actual, judge_model)

    # citation verification and faithfulness checking
    citation_check = verify_citations(actual, citation_map)
    faithfulness_check = check_faithfulness(query, actual, citation_map, judge_model)

    diagnosis_results.append({
        "question": query,
        "expected": expected,
        "actual": actual,
        "correct": correct,
        "recall_hit": recall_hit,
        "has_hallucinated_citation": citation_check["has_hallucinated_citation"],
        "invalid_tags": citation_check["invalid_tags"],
        "faithfulness_supported": faithfulness_check["supported"],
    })

  # step 3: print the diagnostic report and save
  print(f"\n{'='*60}")
  print(f"Answer Quality Diagnosis | top_k = {top_k}, reranker_top_k = {reranker_top_k}")
  print(f"{'='*60}\n")

  correct_count = 0
  for r in diagnosis_results:
    correct_count += r["correct"]

    print(f"Question: {r['question']}")
    print(f"  expected     : {r['expected']}")
    print(f"  actual       : {r['actual'].strip()}")
    print(f"  correct      : {'✅' if r['correct'] else '❌'}")
    print(f"  citation OK  : {'❌ 幻覺引用 ' + str(r['invalid_tags']) if r['has_hallucinated_citation'] else '✅'}")
    print(f"  faithfulness : {'✅' if r['faithfulness_supported'] else '❌'}")

    if not r["correct"]:
      if r["recall_hit"] is False:
        print(f"problem source: Retrieval, recall does not hit, come back to Phase 1")

      elif r["recall_hit"] is None:
        print(f"the expected answer is 'I don't know', check if the actual answer is semantically equivalent to the expected one")

      else:
        print(f"Recall hits but the answer is wrong, see below")
        print(f"if the actual answer is in fact correct: Judge, consider more powerful judge models")
        print(f"if the actual answer is truly incorrect: Prompt, consider to change the prompt_builder")
    else:
      print(f"✅ All pass")

    print()

  score = correct_count / len(diagnosis_results)
  citation_validity = sum(not r["has_hallucinated_citation"] for r in diagnosis_results) / len(diagnosis_results)
  faithfulness_score = sum(r["faithfulness_supported"] for r in diagnosis_results) / len(diagnosis_results)

  print(f"{'=' * 60}")
  print(f"Answer Quality: {score:.3f}")
  print(f"{'=' * 60}\n")

  # record the results
  save_experiment(
      params = {"chunk_size": chunk_size,
                "chunk_overlap": chunk_overlap,
                "top_k": top_k,
                "reranker_top_k": reranker_top_k,
                "embedding_model": embedding_model,
                "reranker_model": reranker_model,
                "llm_model": llm_model,
                "judge_model": judge_model},
      metrics = {"answer_quality": round(score, 3),
                "citation_validity": round(citation_validity, 3),
                "faithfulness": round(faithfulness_score, 3)},
      notes = notes
  )

Writing RAG_module/answer_quality_debugger.py

In [ ]:
## run the answer-quality debugger
from RAG_module.vector_store import create_vector_store
from RAG_module.evaluator import load_eval_dataset
from RAG_module.gemini_client import setup_gemini
from RAG_module.answer_quality_debugger import answer_quality_debug

answer_quality_configs = {
    'chunk_size': 550,
    'chunk_overlap': 150,
    'embedding_model': "BAAI/bge-m3",
    'embedding_dim': 1024,
    'top_k': 12,
    'reranker_model': "BAAI/bge-reranker-v2-m3",
    'reranker_top_k': 8,
    'llm_model': "llama-3.1-8b-instant",
    'judge_model': "openai/gpt-oss-120b"
}

try:
  qdrant_client.close()

except:
  pass

qdrant_client = create_vector_store()
dataset = load_eval_dataset()
gemini_client = setup_gemini()

answer_quality_debug(
    qdrant_client = qdrant_client,
    gemini_client = gemini_client,
    dataset = dataset,
    chunk_size = answer_quality_configs['chunk_size'],
    chunk_overlap = answer_quality_configs['chunk_overlap'],
    embedding_model = answer_quality_configs['embedding_model'],
    embedding_dim = answer_quality_configs['embedding_dim'],
    reranker_model = answer_quality_configs['reranker_model'],
    top_k = answer_quality_configs['top_k'],
    reranker_top_k = answer_quality_configs['reranker_top_k'],
    llm_model = answer_quality_configs['llm_model'],
    judge_model = answer_quality_configs['judge_model']
)

[ocr_correction] 貨幣政策工具.pdf（page_label = 12）：「店 、1,000」→「500萬元、1,000」
[ocr_correction] 貨幣政策工具.pdf（page_label = 13）：「國庫六 發 行條例」→「國庫券發行條例」
some known errors are corrected for the documents.

Loading weights:   0%|          | 0/393 [00:00<?, ?it/s]

1/5: [LLM] encounters rate limit, wait for 2 seconds to retry...
1/5: [LLM] encounters rate limit, wait for 2 seconds to retry...

============================================================
Answer Quality Diagnosis | top_k = 12, reranker_top_k = 8
============================================================

Question: 依據「因應氣候變遷策略方案」，中央銀行因應氣候變遷的政策目標有哪兩項？
  expected     : 強化經濟金融體系因應氣候變遷風險之韌性；協助經濟體系順利轉型至永續之綠色經濟
  actual       : 根據上述文獻，我們可以得出以下結論：

中央銀行因應氣候變遷的政策目標分別為：

1. 「強化經濟金融體系因應氣候變遷風險之韌性」
2. 「協助經濟體系順利轉型至永續之綠色經濟」

這兩個政策目標根據文獻[S1]、[S3]、[S4]、[S5]和[S8]所提到的「因應氣候變遷策略方案」得出的結論[source]。
  correct      : ✅
  citation OK  : ✅
  faithfulness : ✅
✅ All pass

Question: NGFS（綠色金融體系網絡）是在哪一年、於哪個城市成立的？
  expected     : 2017年12月，在巴黎（第一次「一個星球峰會」中）成立
  actual       : NGFS（綠色金融體系網絡）是在 2017 年 12 月，在巴黎成立的，源自於該年的第一個 " 一個星球峰會" (One Planet Summit)。 [S1] (因應氣候變遷策略方案.pdf 第20頁) [S29]
  correct      : ✅
  citation OK  : ❌ 幻覺引用 {'[S29]'}
  faithfulness : ✅
✅ All pass

Question: 依據瑞士再保險公司資料，近10年(2012-2021年)全球極端氣候災害造成的經濟損失是多少？跟1980年代相比呢？
  expected     : 近10年(2012-2021年)約1.93兆美元，遠高於1980年代的2,140億美元
  actual       : 根據資料 [S1]和資料 [S2]，近 10 年(2012-2021 年)全球極端氣候災害造成的經濟損失達到 1.93 兆美元，而 1980 年代的經濟損失則為 2,140 億美元。
  correct      : ✅
  citation OK  : ✅
  faithfulness : ✅
✅ All pass

Question: 「綠天鵝」(green swan)這個詞指的是什麼？
  expected     : 指氣候相關風險引發之系統性金融危機，具有災難性及不可逆性
  actual       : 綠天鵝(green swan)是一個指稱氣候相關風險引發之系統性金融危機，且具有災難性及不可逆性的詞彙，與傳統的天鵝效應(credit crunch)不同。

根據 [S2]，氣候變遷風險之來源包括有形風險 (physical risks) 及轉型風險 (transition risks)，該等風險透過經濟部門傳遞至金融體系，進而推升金融風險，並可能引發有「綠天鵝」(green swan)之稱的系統性金融危機，影響金融體系穩定。

而根據 [S3]，主要國家央行對於是否將氣候變遷風險納入央行政策操作架構尚無共識，但考量氣候變遷可能影響金融穩定及貨幣政策有效性，因此積極評估氣候變遷風險對經濟金融之衝擊，並將其納入審慎監理範疇。
  correct      : ✅
  citation OK  : ✅
  faithfulness : ✅
✅ All pass

Question: 依據「貨幣政策工具」，銀行向央行申請短期融通，期限最長不能超過幾天？
  expected     : 十天
  actual       : 根據[S2] (貨幣政策工具.pdf 第8頁)的記載，銀行向央行申請短期融通，期限最長不得超過10天。

 Source: [S2]
  correct      : ✅
  citation OK  : ✅
  faithfulness : ✅
✅ All pass

Question: 我國中央銀行儲蓄券最後是什麼時候全部到期兌償完畢的？此後有沒有再發行？
  expected     : 民國81年1月全部到期兌償完畢，此後未再發行
  actual       : 根據給定的文檔[S1]第 10 页，中 央银 行儲蓄券最後是民國 81 年 1 月全部到期兌償完畢。此後沒有再發行。
  correct      : ✅
  citation OK  : ✅
  faithfulness : ✅
✅ All pass

Question: 央行重貼現的合格票據中，工商業票據跟農業票據的重貼現期限最長分別是幾天？
  expected     : 工商業票據最長不得超過九十天，農業票據最長不得超過一百八十天
  actual       : 根據 [S1] 文摘描述, 工商業票據的重貼現期限最長不得超過九十天, 農業票據最長不得超過一百八十天。
  correct      : ✅
  citation OK  : ✅
  faithfulness : ✅
✅ All pass

Question: 依據「中華民國支付及清算系統」，截至民國111年底，我國信用卡流通卡數約幾張？
  expected     : 約5,624萬張
  actual       : 根據 [S2] (中華民國支付及清算系統.pdf 第12頁)，截至民國 111 年底，流通卡數約 1.18 億張。

因此，截至民國 111 年底，我國信用卡流通卡數約 118,000,000 張。
  correct      : ❌
  citation OK  : ✅
  faithfulness : ❌
Recall hits but the answer is wrong, see below
if the actual answer is in fact correct: Judge, consider more powerful judge models
if the actual answer is truly incorrect: Prompt, consider to change the prompt_builder

Question: 在支付清算領域中，「集中交易對手」（central counterparty, CCP）的定義是什麼？
  expected     : 擔任某些特定契約（例如在特定交易所執行之契約）所有賣方之買方及所有買方之賣方的機構
  actual       : 根據 [S2],集中交易對手(CCP)是一種機構，擔任某些特定契約（如在特定交易所執行之契約）所有賣方之買方及所有買方之賣方。[S2]

根據 [S6], CCP是在一個或多個金融市場中，介於契約交易對手之間的個體，成為所有賣方之買方及所有買方之賣方，具集中風險及風險管理的職責。[S6]

所以，我們可以確認「集中交易對手」（central counterparty, CCP）的定義是：在一或多個資訊市場中，作為交易者之間的中間人，負責管理市場風險和風險管理。

參考[S2], [S6]
  correct      : ✅
  citation OK  : ✅
  faithfulness : ✅
✅ All pass

Question: 依據這批文件，台灣2026年的信用卡循環利率上限是多少？
  expected     : I don't know
  actual       : I don't know.
  correct      : ✅
  citation OK  : ✅
  faithfulness : ❌
✅ All pass

Question: 截至民國111年底，同資系統參加單位共幾家？包括哪些類型的機構？
  expected     : 共86家，包括71家銀行、8家票券金融公司、中華郵政公司，以及財金公司、票交所、證交所、櫃買中心、集保結算所及聯卡中心等6家結算機構
  actual       : 截至民國111年底，同資系統參加單位共 86 家，包括 71 家銀行、8 家票券金融公司、中華郵政公司，以及財金公司、票交所、證交所、櫃買中心、集保結算所及聯卡中心等6 家結算機構。

[S1]
  correct      : ✅
  citation OK  : ✅
  faithfulness : ✅
✅ All pass

Question: 「QR Code共通支付標準」是哪一年由財金公司協同金融機構制定的？
  expected     : 民國106年
  actual       : 民國 106 年 [S1] (中華民國支付及清算系統.pdf 第36頁).
  correct      : ✅
  citation OK  : ✅
  faithfulness : ✅
✅ All pass

Question: 信用卡結算系統由哪個機構營運？自哪一年幾月起連結同資系統辦理清算？
  expected     : 由聯卡中心（聯合信用卡處理中心）營運，自民國102年11月起連結同資系統辦理清算
  actual       : 根據 [S1] (中華民國支付及清算系統.pdf 第24頁) 的描述，信用卡結算系統由聯卡中心營運。自民國 102 年 11 月起，聯卡中心連結同資系統辦理清算。

所以答案是：聯卡中心，並在民國 102 年 11 月起連結同資系統辦理清算。
  correct      : ✅
  citation OK  : ✅
  faithfulness : ✅
✅ All pass

Question: 民國111年信用卡結算系統處理的交易金額跟簽帳筆數約多少？
  expected     : 交易金額約1.6兆元，筆數約13.1億筆
  actual       : 根據 [S2] 中的資訊，我們可以得知民國 111 年信用卡結算系統處理的交易金額約為 1.6 兆元，簽帳筆數約為 13.1 億筆。

交易金額：約 1.6 兆元 [S2]
簽帳筆數：約 13.1 億筆 [S2]

資料來源：同樣的數據也出現於 [S1]。
  correct      : ✅
  citation OK  : ✅
  faithfulness : ✅
✅ All pass

Question: 依據「一國支付系統發展之一般準則」，一般準則共有幾項？分成哪四大面向？
  expected     : 共14項，分成銀行體系、計畫、制度性架構、基礎設施四大面向
  actual       : 根據提供的文본，一國支付系統發展之一般準則共有14項。根據[S4]的描述，這14項準則分成四大面向：

1. 銀行體系與一國支付系統之發展
2. 規劃一國支付系統之發展
3. 發展一國支付系統之制度性架構
4. 發展一國支付系統之基礎設施

[S3]文本中也提到這四大面向，並在第4頁列出相關準則如下：

* 銀行體系與一國支付系統之發展：準則 1 到準則 2
* 規劃一國支付系統之發展：準則 3 到準則 6
* 發展一國支付系統之制度性架構：準則 7 到準則 10
* 發展一國支付系統之基礎設施：準則 11 到準則 14
  correct      : ✅
  citation OK  : ✅
  faithfulness : ✅
✅ All pass

Question: 「一國支付系統發展之一般準則」裡的準則1，名稱是什麼？
  expected     : 維持中央銀行居於核心地位
  actual       : 維持中央銀行居於核心地位 [S2][S3][S4][S6].
  correct      : ✅
  citation OK  : ✅
  faithfulness : ✅
✅ All pass

Question: 「一國支付系統發展之一般準則」裡的準則10，名稱是什麼？
  expected     : 加強法律之確定性
  actual       : 根據[S1]的資訊，準則 10 的名稱為：加強法律之確定性：為一國支付系統建立透明、周延及健全的法規架構。
  correct      : ✅
  citation OK  : ✅
  faithfulness : ✅
✅ All pass

Question: 「一國支付系統發展之一般準則」裡的準則5，名稱是什麼？
  expected     : 制訂明確之優先順序
  actual       : 根據[S4] (一國支付系統發展之一般準則.pdf 第4頁)，準則 5 名為「制訂明確之優先順序：策略性計劃並制訂一國支付系統發展的優先順序。」
根據[S5] (一國支付系統發展之一般準則.pdf 第96頁)，準則 5 名為「制訂明確之優先順序：策略性計劃並制訂一國支付系統發展的優先順序。」
根據[S6] (一國支付系統發展之一般準則.pdf 第10頁)，準則 5 名為「制訂明確之優先順序：策略性計劃並制訂一國支付系統發展的優先順序。」
根據[S7] (一國支付系統發展之一般準則.pdf 第11頁)，準則 5 名為「制訂明確之優先順序：策略性計劃並制訂一國支付系統發展的優先順序。」
  correct      : ✅
  citation OK  : ✅
  faithfulness : ✅
✅ All pass

Question: CLS是什麼機制的縮寫？主要用什麼方式清算外匯交易？
  expected     : CLS是Continuous Linked Settlement（持續連結清算）的縮寫，透過CLS銀行的會計帳簿，以款對款同步收付（PVP）方式進行資金撥轉
  actual       : 根據[S1], CLS是證券集中保管機構(Central Securities Depository, CSD)與大額支付系統(Large-Value Payment System, LVPS)之間的連結關係,[S1] 也指出，持續連結清算（Continuous Linked Settlement, CLS）系統係依賴CLS銀行與CLS各合格清算幣別之中央銀行所建立的帳戶關係，使外匯交易透過CLS銀行的會計帳簿，以款對款同步收付(Payment Versus Payment, PVP)方式進行資金撥轉。

因此，CLS是清算多國貨幣的連結機制，主要用以PVP的方式清算外匯交易。
  correct      : ✅
  citation OK  : ✅
  faithfulness : ❌
✅ All pass

Question: 依據「支付與清算系統間之相互依存關係」，CPSS提出因應相互依存關係的三項重大挑戰是什麼？
  expected     : (i)採取廣泛的風險管理視野；(ii)系統、機構或服務提供者具備之風險控管機制應能與其在全球基礎設施扮演之角色相稱；(iii)在相互依存利害關係人間進行廣泛協調
  actual       : 根據本報告書，CPSS提出因應相互依存關係的三項重大挑戰如下：

1. **擴大風險管理的視野**：系統營運者、金融機構及第三人服務提供者應定期檢討因相互依存關係所承受及加倍其他業者之風險（第 14 頁）。
2. **系統、機構或服務提供者的風險控管機制應能與其在全球基礎設施扮演之角色相稱**：中央銀行應考量其監管政策所涵蓋相關當事人的範圍是否足夠，並檢討各種藉以落實該期望的方式（第 88 頁）。
3. **在相互依存利害關係人間進行廣泛的協調**：多個支付與清算系統間的相互依存性，不僅源自系統間之直接關係，也伴隨金融機構於多個系統內進行支付與清算活動產生之間接關係，以及更廣泛的因素（第 88 頁）。

(S1, S2, S3, S4, S5)
  correct      : ✅
  citation OK  : ✅
  faithfulness : ✅
✅ All pass

Question: SWIFT的中文全稱是什麼？
  expected     : 環球銀行金融電信協會
  actual       : 環球銀行金融電信協會（SWIFT） [S1][S3][S4][S5][S6][S7][S8]
  correct      : ✅
  citation OK  : ✅
  faithfulness : ✅
✅ All pass

Question: 依據「貨幣政策工具」，中央銀行的貨幣政策工具主要依序包括哪五大類制度？
  expected     : 準備金制度、貼現窗口制度、公開市場操作、金融機構轉存款、選擇性信用管理
  actual       : 根據「貨幣政策工具.pdf 第16頁」 [S2], 中央銀行的貨幣政策工具主要依序包括：

1. 準備金制度
2. 貼現窗口制度
3. 公開市場操作
4. 金融機構轉存款
5. 選擇性信用管理

此外，還有提到流動準備制度，但是它不是中央銀行的貨幣政策工具，而是流動準備制度的內涵與業務操作 [S3]。

因此，依據「貨幣政策工具.pdf 第16頁」 [S2], 中央銀行的貨幣政策工具主要依序包括前五大類制度。
  correct      : ✅
  citation OK  : ✅
  faithfulness : ✅
✅ All pass

Question: 支票存款、活期存款、儲蓄存款、定期存款的準備率法定上限各為多少？
  expected     : 支票存款25%、活期存款25%、儲蓄存款15%、定期存款15%（其他各種負債25%）
  actual       : 根據 [S1] (貨幣政策工具.pdf 第3頁), 支票存款、活期存款、儲蓄存款、定期存款的準備率法定上限分別為25%、25%、15%、15%。
  correct      : ✅
  citation OK  : ✅
  faithfulness : ✅
✅ All pass

Question: 中央銀行定期存單發行面額分為哪三種？
  expected     : 500萬元、1,000萬元、與1億元三種
  actual       : 根據 [S1] 的描述，中央銀行定期存單發行面額分為 500 萬元、1,000 萬元和 1 億元等三種。

(S1)貨幣政策工具.pdf 第12頁
  correct      : ✅
  citation OK  : ✅
  faithfulness : ✅
✅ All pass

Question: 銀行申請短期融通的金額，每月平均不得超過當月應提存款準備金的多少百分比？
  expected     : 10%
  actual       : 按照 [S1] 的說明，銀行申請短期融通的金額，每月平均不得超過當月應提存款準備金的 10%。
  correct      : ✅
  citation OK  : ✅
  faithfulness : ✅
✅ All pass

Question: 銀行申請擔保放款之再融通，期限最長不能超過幾天？
  expected     : 三百六十天
  actual       : 根據[S1] (貨幣政策工具.pdf 第10頁) 的描述，銀行因承做政府核定並經中央銀行同意的放款、或配合中央銀行貨幣政策承做的放款、或有緊急性資金需求並經中央銀行同意者，可以中央銀行同意的有價證券或存款準備金乙戶為擔保品，申請擔保放款之再融通。該項融通的期限最長不能超過三百六十天。

因此，最終答案是：三百六十天。
  correct      : ✅
  citation OK  : ✅
  faithfulness : ✅
✅ All pass

Question: 民國87年7月後，依據哪個法規的實施，中央銀行不得再發行國庫券？
  expected     : 「短期借款暨國庫券發行條例」
  actual       : 民國87年7月後，依據「短期借款暨國庫券發行條例」的實施，中央銀行不得再發行國庫券。

([S2])
  correct      : ✅
  citation OK  : ✅
  faithfulness : ✅
✅ All pass

Question: 依據「因應氣候變遷策略方案」，氣候變遷風險分為哪兩類？
  expected     : 有形風險(physical risks)及轉型風險(transition risks)
  actual       : 根據[S2] (因應氣候變遷策略方案.pdf 第9頁)，氣候變遷風險分為兩類：有形風險(physical risks)及轉型風險(transition risks)。
  correct      : ✅
  citation OK  : ✅
  faithfulness : ✅
✅ All pass

Question: 本行因應氣候變遷的三大核心策略是什麼？
  expected     : 協助發展綠色永續投融資環境；積極建構本行對氣候議題之專業能力；本行營運與外匯存底管理運用納入氣候風險考量
  actual       : 根據提供的文檔內容， 本行因應氣候變遷的三大核心策略，是協助發展綠色永續投融資環境、積極建構本行對氣候議題之專業能力、以及本行營運與外匯存底管理運用納入氣候風險考量等。

[S2]提到了本行研擬推動三大核心策略， 包括協助發展綠色永續投融資環境、積極建構氣候專業知識、以及將氣候風險納入本行營運與外匯存底管理運用考量等。

[S7] 提到了本行因應氣候變遷之政策架構，其中提到三大核心策略，分別是協助發展綠色永續投融資環境、積極建構本行對氣候議題之專業能力、以及本行營運與外匯存底管理運用納入氣候風險考量等。

[S8] 同時提到本行因應氣候變遷之政策架構，也同樣提到三大核心策略。

因此，根據提供的文檔內容， 本行因應氣候變遷的三大核心策略是：

1. 協助發展綠色永續投融資環境
2. 積極建構本行對氣候議題之專業能力
3. 本行營運與外匯存底管理運用納入氣候風險考量
  correct      : ✅
  citation OK  : ✅
  faithfulness : ✅
✅ All pass

Question: 巴塞爾銀行監理委員會(BCBS)於2022年6月發布了幾項「氣候相關金融風險之有效管理及監理原則」？
  expected     : 18項
  actual       : 根據 [S4] 的內容，BCBS於2022年6月發布18項「氣候相關金融風險之有效管理及監理原則」，供各國參考與遵循，詳情見BCBS (2022) [S4]。

另外，根據 [S1] 的內容，BCBS於2022年6月發布18項原則涵蓋銀行之公司治理、內控架構、資本與流動性適足、風險管理流程、管理監控與呈報、各項風險管理與情境分析，以及金融監理機關之審慎監理要求、責任、權力與功能等不同層面 [S1]。

根據 [S3] 的內容，BCBS於2022年6月發布Principles for the Effective Management and Supervision of Climate-related Financial Risks [S3]。

總的說來，根據給定的內容，BCBS於2022年6月發布了18項或18項關於氣候相關金融風險之有效管理及監理原則的文獻。

故本題的正確答案應為18項。

參考來源： [S3] [S1] [S4]。

最終答案是18。
  correct      : ✅
  citation OK  : ✅
  faithfulness : ✅
✅ All pass

Question: 依據本行2022年6月底的調查，40家本國銀行中有幾家已設立永續金融專責單位？
  expected     : 29家
  actual       : 根據 [S1] 的文檔第 17 頁，依據本行 2022 年 6 月底的調查，已有 29 家銀行或所屬金控公司在內部設立永續金融專責單位。

因此，答案是：**29** 家銀行或所屬金控公司已設立永續金融專責單位。
  correct      : ✅
  citation OK  : ✅
  faithfulness : ✅
✅ All pass

Question: 截至2022年10月3日，NGFS有幾家央行及金融監理機構成為會員？
  expected     : 121家
  actual       : 截至 2022 年 10 月 3 日，全球已有 121 家央行及金融監理機構成為 NGFS 成員，另有 IMF、BIS 等 19 個國際組織以觀察員身分參加。[S1]

因此，NGFS 有 121 家央行及金融監理機構成為會員。
  correct      : ✅
  citation OK  : ✅
  faithfulness : ✅
✅ All pass

Question: 依據「西班牙銀行自治法」，總裁及副總裁的任期為幾年？期滿是否可連任同一職務？
  expected     : 任期為6年，且不得續任同一職務
  actual       : 根據「西班牙銀行自治法」，總裁及副總裁的任期為 6 年，並不得續任同一職務。

[S1]

[S2] 第 1 條第 1 款，明文規定「總裁及副總裁之任期為 6 年，且不得續任同一職務。」

[S3] 第 1 條第 1 款，同樣規定總裁及副總裁的任期為 6 年，並無記载可續任同一職務。

[S4] 第 ? 條，同樣規定總裁及副總裁的任期為 6 年，並無記载可續任同一職務。

[S6] 第 ? 條，同樣指出總裁及副總裁的任期為 6 年，並無記载可續任同一職務。

根據 [S2] 第 4 條第 a 項，總裁及副總裁的任期屆滿時，可由政府決定解任，但不涉及續任同一職務問題，也不涉及連任問題。
  correct      : ✅
  citation OK  : ✅
  faithfulness : ❌
✅ All pass

Question: 依據「南非準備銀行法」，總裁及副總裁的任期為幾年？
  expected     : 任期均為5年；期滿經總統徵詢部長及理事會後，得續任命之，但任期不得逾5年
  actual       : 據南非準備銀行法規定，總裁及副總裁的任期為 5 年。

但也可以續任連任一次，期滿得續派連任 1 次 [S1]、[S7]。

具體而言，根據南非準備銀行法（1989 年）、[S7]和[S8]的規定，總裁及副總裁都須以任意一項任期結束後才可續任連任。
  correct      : ✅
  citation OK  : ✅
  faithfulness : ✅
✅ All pass

Question: 依據「以色列銀行法」，總裁的任期為幾年？期滿後可連任幾次？
  expected     : 任期為5年，期滿得續派連任1次
  actual       : 根據「以色列銀行法」，總裁的任期為 5 年，期滿後可連任至多兩次。

[S6] (各國中央銀行法選輯-2025年版-下冊.pdf 第190頁)
( ) 任期為 5 年，期滿得再任至多兩次任期；


[S2] (各國中央銀行法選輯-2025年版-上冊.pdf 第132頁)
(a) 총裁任期为 5 年，期满得续派连任 1 次。
(b) 副总裁任期为 5 年，期满得续派连任 1 次。但副总裁之任期除已届至者外，应于新任总裁就任满 1 年时终止之；
  correct      : ❌
  citation OK  : ✅
  faithfulness : ❌
Recall hits but the answer is wrong, see below
if the actual answer is in fact correct: Judge, consider more powerful judge models
if the actual answer is truly incorrect: Prompt, consider to change the prompt_builder

Question: 依據「印度尼西亞銀行法」，理事會成員的任期為幾年？
  expected     : 5年
  actual       : 根據 [S2] (各國中央銀行法選輯-2025年版-上冊.pdf 第54頁) 的內容，理事會成員的任期為 3 年。

[source: [S2] ]
  correct      : ❌
  citation OK  : ✅
  faithfulness : ❌
Recall hits but the answer is wrong, see below
if the actual answer is in fact correct: Judge, consider more powerful judge models
if the actual answer is truly incorrect: Prompt, consider to change the prompt_builder

Question: 依據「中華民國中央銀行法」第一條，本行經營之目標有哪四項？
  expected     : 促進金融穩定；健全銀行業務；維護對內及對外幣值之穩定；於上列目標範圍內，協助經濟之發展
  actual       : 依據[S2] (各國中央銀行法選輯-2025年版-上冊.pdf 第180頁)，本行經營之目標有四項：

一、促進金融穩定。
二、健全銀行業務。
三、維護對內及對外幣值之穩定。
四、於上列目標範圍內，協助經濟之發展。

源自[S2] (各國中央銀行法選輯-2025年版-上冊.pdf 第180頁)。
  correct      : ✅
  citation OK  : ✅
  faithfulness : ✅
✅ All pass

Question: 「各國中央銀行法選輯（2025年版）」上冊跟下冊分別收錄了哪幾個國家的中央銀行法？
  expected     : 上冊收錄西班牙、土耳其、南非、以色列；下冊收錄挪威、阿拉伯聯合大公國、印尼、巴哈馬
  actual       : 根據《各國中央銀行法選輯（2025 年版）》（中英對照本）上下冊的內容，以下是收錄的國家：

上冊收錄了：
西班牙銀行自治法、土耳其共和國中央銀行法、南非準備銀行法、以色列銀行法（第四頁）
挪威銀行及貨幣制度法（中央銀行法）、阿拉伯大公國中央銀行及金融機構組織與業務法、印度尼西亞銀行法、巴哈馬中央銀行法 (第四頁、第200頁)

下冊收錄了：
挪威、阿拉伯聯合大公國、印度尼西亞、巴哈馬（第四頁）

因此，上冊有 4 個國家的中央銀行法，而下冊有 4 個國家的中央銀行法。

上冊：西班牙、土耳其、南非、以色列（第200頁）
下冊：挪威、阿拉伯聯合大公國、印度尼西亞、巴哈馬（第200頁）

(S1)(S6)
  correct      : ✅
  citation OK  : ✅
  faithfulness : ✅
✅ All pass

Question: 依據這批文件，2026年台灣中央銀行的重貼現率是多少？
  expected     : I don't know
  actual       : [S6] (各國中央銀行法選輯-2025年版-上冊.pdf 第64頁)指出，理事會依第 4 條決定之黃金及外匯買賣價格，以及依第 22 條第（3）款及第（5）款譯註 2 關於決策，應於政府公報。但是，這段描述並無明確指出重貼現率。[S7] (中華民國支付及清算系統.pdf 第35頁) 提到本行將持續藉由...彈性調整支付及清算系統相關規範，以符合市場需求，但是這段描述也不明確指出重貼現率。

[S1] (貨幣政策工具.pdf 第7頁) 提到，實施至今的流動準備制度，雖然已提高為 7%，但沒有對重貼現率有任何描述。

[S3] (貨幣政策工具.pdf 第8頁)指出，重貼現利息的預扣，依中央銀行公告的重貼現率計算。但是在這個文件中，並沒有提到重貼現率的具體數值。

根據這些資訊，我們無法從這些文件中確立2026年台灣中央銀行的重貼現率是多少。
  correct      : ✅
  citation OK  : ✅
  faithfulness : ✅
✅ All pass

Question: 依據這批文件，美國聯邦準備法（Federal Reserve Act）對總裁任期有何規定？
  expected     : I don't know
  actual       : I don't know.
  correct      : ✅
  citation OK  : ✅
  faithfulness : ❌
✅ All pass

============================================================
Answer Quality: 0.925
============================================================

Experiment #3 saved.

In [ ]:
## print the experiments of answer-quality debugging
from RAG_module.experiment_tracker import show_experiments
show_experiments()

,id,timestamp,chunk_size,chunk_overlap,top_k,reranker_top_k,embedding_model,reranker_model,llm_model,judge_model,recall,notes,answer_quality,citation_validity,faithfulness
0,1,2026-07-22 04:02,550,150,12,8,BAAI/bge-m3,BAAI/bge-reranker-v2-m3,llama-3.1-8b-instant,qwen/qwen3.6-27b,0.97,,NaN,NaN,NaN
1,2,2026-07-22 04:24,550,150,12,8,BAAI/bge-m3,BAAI/bge-reranker-v2-m3,llama-3.1-8b-instant,qwen/qwen3.6-27b,NaN,,0.00,1.00,0.00
2,3,2026-07-22 04:47,550,150,12,8,BAAI/bge-m3,BAAI/bge-reranker-v2-m3,llama-3.1-8b-instant,openai/gpt-oss-120b,NaN,,0.93,0.97,0.82

## 評估主程式
* `main.py` 是互動式的設計；但 RAG 模型表現評估是需要自動跑完所有評估資料問題，與 `main.py` 不相容。
* 可視為經歷過調參的最終測驗，測驗結果做為是否能拿到證照的依據。
> * 診斷時經歷各種寫考古題與檢討的過程，運行評估主程式就像是參加正式測驗。

In [ ]:
import RAG_module.api
from RAG_module.retrieval_pipeline import run_retrieval
from RAG_module.evaluator import load_eval_dataset, eval_retrieval, eval_answer
from RAG_module.bm25_retriever import BM25Retriever
from RAG_module.reranker import Reranker
from RAG_module.vector_store import create_vector_store
from RAG_module.loader import load_documents
from RAG_module.chunker import create_nodes
from RAG_module.metadata_loader import load_document_metadata
from RAG_module.experiment_tracker import save_experiment, print_experiments
from RAG_module.prompt_builder import build_prompt
from RAG_module.gemini_client import setup_gemini, ask_gemini
from RAG_module.config import COLLECTION_NAME


evaluation_configs = {
    'chunk_size': 256,
    'chunk_overlap': 50,
    'embedding_model': "BAAI/bge-m3",
    'embedding_dim': 1024,
    'top_k': 8,
    'reranker_model': "cross-encoder/ms-marco-MiniLM-L-6-v2",
    'reranker_top_k': 8,
    'llm_model': "llama-3.1-8b-instant",
    'judge_model': "llama-3.3-70b-versatile"
}

# 0: close any possibly existent Qdrant client
try:
  qdrant_client.close()

except:
  pass


# 1: initializations
qdrant_client = create_vector_store()
documents = load_documents()
nodes = create_nodes(documents, evaluation_configs['chunk_size'], evaluation_configs['chunk_overlap'])

metadata_lookup = load_document_metadata()
for node in nodes:
  file_name = node.metadata.get("file_name")
  extracted = metadata_lookup.get(file_name, {})
  node.metadata.update(extracted)

bm25_retriever = BM25Retriever(nodes)
reranker = Reranker(evaluation_configs['reranker_model'])
gemini_client = setup_gemini()


# 2: define retrieve_fn, retrieve_fn_no_rerank and reg_fn
# retrieve_fn: extract the texts from the output of reranking
def retrieve_fn(query, configs, metadata_filters = None):
  result = run_retrieval(qdrant_client,
                         bm25_retriever,
                         reranker,
                         query,
                         configs['embedding_model'],
                         configs['top_k'],
                         configs['reranker_top_k'],
                         metadata_filters = metadata_filters)
  return [chunk["text"] for chunk in result["reranked_chunks"]]


def retrieve_fn_no_rerank(query, configs, metadata_filters = None):
  query_vector = create_query_embedding(query, configs['embedding_model'])
  query_filter = build_metadata_filter(metadata_filters)
  dense_results = search_points(qdrant_client,
                                COLLECTION_NAME,
                                query_vector,
                                limit = configs['top_k'],
                                filters = query_filter).points
  bm25_results = bm25_retriever.retrieve(query, limit = configs['top_k'], metadata_filters = metadata_filters)

  dense_chunks = {p.payload["text"]: _make_chunk(p.payload["text"],
                                                 {k: v for k, v in p.payload.items() if k != "text"},
                                                 p.score) for p in dense_results}
  bm25_chunks = {node.text: _make_chunk(node.text, node.metadata, score) for node, score in bm25_results}

  merged = {**dense_chunks, **bm25_chunks}  # the union in dictionary
  all_chunks = list(merged.values())

  return [chunk["text"] for chunk in all_chunks]


def rag_fn_with_citation(query, configs, metadata_filters = None):
  result = run_retrieval(qdrant_client,
                         bm25_retriever,
                         reranker,
                         query,
                         configs['embedding_model'],
                         configs['top_k'],
                         configs['reranker_top_k'],
                         metadata_filters = metadata_filters)
  prompt, citation_map = build_prompt(query, result["reranked_chunks"])
  answer = ask_gemini(gemini_client, prompt, configs['llm_model'])
  return answer, citation_map


# 3: evaluation stage 1: recall
with_rerank = True
dataset = load_eval_dataset()
recall, results = eval_retrieval(dataset, retrieve_fn, evaluation_configs)

if with_rerank:
  print(f"Recall@{evaluation_configs['reranker_top_k']}: {recall:.2f}\n")

else:
  print(f"Recall@{evaluation_configs['top_k']}: {recall:.2f}\n")


for r in results:
  status = "✅" if r["hit"] else "❌"
  print(f"{status} {r['question']}")


# 4: evaluation stage 2: answer quality and other secondary metrics
answer_scores, answer_results = eval_answer(dataset, rag_fn_with_citation, evaluation_configs)

aq_score = answer_scores["answer_quality"]
citation_validity = answer_scores["citation_validity"]
faithfulness_score = answer_scores["faithfulness"]

print(f"Answer Quality: {aq_score:.2f}")
print(f"Citation Validity: {citation_validity:.2f}")
print(f"Faithfulness: {faithfulness_score:.2f}\n")

for r in answer_results:
  status = "✅" if r["correct"] else "❌"
  print(f"{status} {r['question']}")
  print(f"   expected: {r['expected']}")
  print(f"   actual  : {r['actual'].strip()}")
  if r["has_hallucinated_citation"]:
    print(f"   ⚠️ invalid tags: {r['invalid_tags']}")
  if not r["faithfulness_supported"]:
    print(f"   ⚠️ 這一輪檢索到的來源，合起來似乎無法支持這個回答")
  print()
  print()

# 5: record the experiment result
params = {
    "chunk_size": evaluation_configs['chunk_size'],
    "chunk_overlap": evaluation_configs['chunk_overlap'],
    "top_k": evaluation_configs['top_k'],
    "reranker_top_k": evaluation_configs['reranker_top_k'],
    "embedding_model": evaluation_configs['embedding_model'],
    "reranker_model": evaluation_configs['reranker_model'],
    "llm_model": evaluation_configs['llm_model'],
    "judge_model": evaluation_configs['judge_model']
}

metrics = {
    "recall": round(recall, 2),
    "answer_quality": round(aq_score, 2),
    "citation_validity": round(citation_validity, 2),
    "faithfulness": round(faithfulness_score, 2)
}

save_experiment(params, metrics, notes = "")

Loading weights:   0%|          | 0/105 [00:00<?, ?it/s]

Recall@8: 0.78

✅ 依據「因應氣候變遷策略方案」，中央銀行因應氣候變遷的政策目標有哪兩項？
✅ NGFS（綠色金融體系網絡）是在哪一年、於哪個城市成立的？
✅ 依據瑞士再保險公司資料，近10年(2012-2021年)全球極端氣候災害造成的經濟損失是多少？跟1980年代相比呢？
✅ 「綠天鵝」(green swan)這個詞指的是什麼？
❌ 依據「貨幣政策工具」，銀行向央行申請短期融通，期限最長不能超過幾天？
✅ 我國中央銀行儲蓄券最後是什麼時候全部到期兌償完畢的？此後有沒有再發行？
✅ 央行重貼現的合格票據中，工商業票據跟農業票據的重貼現期限最長分別是幾天？
❌ 依據「中華民國支付及清算系統」，截至民國111年底，我國信用卡流通卡數約幾張？
✅ 在支付清算領域中，「集中交易對手」（central counterparty, CCP）的定義是什麼？
Answer Quality: 0.80
Citation Validity: 1.00
Faithfulness: 0.80

✅ 依據「因應氣候變遷策略方案」，中央銀行因應氣候變遷的政策目標有哪兩項？
   expected: 強化經濟金融體系因應氣候變遷風險之韌性；協助經濟體系順利轉型至永續之綠色經濟
   actual  : 根據[S2](因應氣候變遷策略方案.pdf 第5頁)的描述，中央銀行將「強化經濟金融體系因應氣候變遷風險之韌性」及「協助經濟體系順利轉型至永續之綠色經濟」訂為因應氣候變遷之政策目標。

因此，中央銀行因應氣候變遷的政策目標是：

1. 強化經濟金融體系因應氣候變遷風險之韌性 [S2]
2. 協助經濟體系順利轉型至永續之綠色經濟 [S2]

[source: S2]


❌ NGFS（綠色金融體系網絡）是在哪一年、於哪個城市成立的？
   expected: 2017年12月，在巴黎（第一次「一個星球峰會」中）成立
   actual  : NGFS（綠色金融體系網絡）是在 2017 年，在巴黎成立的。

根據上述文獻 [S1] (因應氣候變遷策略方案.pdf 第20頁)，NGFS 係於 2017 年 12 月在巴黎舉行之第一次「一個星球峰會(One Planet Summit) 」中成立。

[S1] (因應氣候變遷策略方案.pdf 第20頁)

（Source： [S1]）


✅ 依據瑞士再保險公司資料，近10年(2012-2021年)全球極端氣候災害造成的經濟損失是多少？跟1980年代相比呢？
   expected: 近10年(2012-2021年)約1.93兆美元，遠高於1980年代的2,140億美元
   actual  : 根據瑞士再保險公司資料統計，近10年(2012-2021年)全球極端氣候災害造成之經濟損失大幅攀升至1.93兆美元，遠高於1980年代之2,140億美元 [S1] (因應氣候變遷策略方案.pdf第9頁)。


✅ 「綠天鵝」(green swan)這個詞指的是什麼？
   expected: 指氣候相關風險引發之系統性金融危機，具有災難性及不可逆性
   actual  : 綠天鵝(Green Swan)是一個代表系統性金融危機的術語，特別是由氣候相關風險引發的災難性和不可逆性事件。

根據[S2]，綠天鵝是指氣候相關風險引發之系統性金融危機，且具有災難性及不可逆性。

同樣地，根據[S6]，綠天鵝係指氣候相關風險引發之系統性金融危機，且具有災難性及不可逆性。


✅ 依據「貨幣政策工具」，銀行向央行申請短期融通，期限最長不能超過幾天？
   expected: 十天
   actual  : 依據 [S6], 銀行向中央銀行申請短期融通，期限不能超過十天。

[S6] (貨幣政策工具.pdf 第8頁)


✅ 我國中央銀行儲蓄券最後是什麼時候全部到期兌償完畢的？此後有沒有再發行？
   expected: 民國81年1月全部到期兌償完畢，此後未再發行
   actual  : 根據 [S6], 中央銀行儲蓄券最後於民國81 年 1 月全部到期兌償完畢。此後未再發行。

[source: S6]


✅ 央行重貼現的合格票據中，工商業票據跟農業票據的重貼現期限最長分別是幾天？
   expected: 工商業票據最長不得超過九十天，農業票據最長不得超過一百八十天
   actual  : 根據 [S6] (貨幣政策工具.pdf 第8頁), 工商業票據最長不得超過九十天, 農業票據最長不得超過一百八十天。

因此,央行重貼現的合格票據中，工商業票據和農業票據的重貼現期限最長分別是九十天和一百八十天。

[S6]


❌ 依據「中華民國支付及清算系統」，截至民國111年底，我國信用卡流通卡數約幾張？
   expected: 約5,624萬張
   actual  : I don't know.
   ⚠️ 這一輪檢索到的來源，合起來似乎無法支持這個回答


✅ 在支付清算領域中，「集中交易對手」（central counterparty, CCP）的定義是什麼？
   expected: 擔任某些特定契約（例如在特定交易所執行之契約）所有賣方之買方及所有買方之賣方的機構
   actual  : 根據[S2]和[S4],集中交易對手(CCP)的定義如下:

集中交易對手(CCP)
擔任某些特定契約（例如在特定交易所執行之契約）所有賣方之買方及所有買方之賣方的機構。
（根據[S2],第115頁）

或

金融市場基礎設施應有效地衡量、監視及管理其對參加者的信用曝險，以及源自其支付、結算及清算過程的信用曝險。集中交易對手(central counterparty，CCP)擔任某些特定交易（如在特定交易所執行之交易）所有賣方之買方及所有買方之賣方的機構。（根據[S4],第38頁）

Source: [S2], [S4]


✅ 依據這批文件，台灣2026年的信用卡循環利率上限是多少？
   expected: I don't know
   actual  : I don't know.
   ⚠️ 這一輪檢索到的來源，合起來似乎無法支持這個回答


Experiment #3 saved.

In [ ]:
## print the experiments of the final evaluation
from RAG_module.experiment_tracker import show_experiments
show_experiments()

,id,timestamp,chunk_size,chunk_overlap,top_k,reranker_top_k,embedding_model,reranker_model,llm_model,judge_model,recall,notes,answer_quality,citation_validity,faithfulness
0,1,2026-07-20 08:41,256,50,8,8,BAAI/bge-m3,BAAI/bge-reranker-v2-m3,llama-3.1-8b-instant,llama-3.3-70b-versatile,0.89,,NaN,NaN,NaN
1,2,2026-07-20 08:47,256,50,8,8,BAAI/bge-m3,BAAI/bge-reranker-v2-m3,llama-3.1-8b-instant,llama-3.3-70b-versatile,NaN,,0.9,1.0,0.9
2,3,2026-07-20 08:52,256,50,8,8,BAAI/bge-m3,cross-encoder/ms-marco-MiniLM-L-6-v2,llama-3.1-8b-instant,llama-3.3-70b-versatile,0.78,,0.8,1.0,0.8